// Code generated by go-asyncapi tool. DO NOT EDIT.

package schemas

type AuthEvent struct {
	// EventType--The type of the event
	EventType string `json:"eventType"`
	// ID--Unique identifier for the event.
	ID           int          `json:"id"`
	AuthRequest  AuthRequest  `json:"authRequest"`
	AuthResponse AuthResponse `json:"authResponse"`
}
