// Code generated by go-asyncapi tool. DO NOT EDIT.

package schemas

type AuthRequest struct {
	// Username--The username of the user requesting authentication.
	Username string `json:"username"`
	// Password--The password of the user requesting authentication.
	Password string `json:"password"`
}
