// Code generated by go-asyncapi tool. DO NOT EDIT.

package schemas

type AuthResponse struct {
	// Success--Indicates whether the authentication was successful.
	Success bool `json:"success"`
	// Message--A message providing additional information about the authentication result.
	Message string `json:"message"`
}
