// Code generated by go-asyncapi tool. DO NOT EDIT.

package http

import (
	"github.com/bdragon300/go-asyncapi/run"
)

import (
	"context"
	"net/url"
)

func NewProducer(serverURL *url.URL, bindings *ServerBindings, security run.AnySecurityScheme) *ProduceClient {
	return &ProduceClient{
		bindings:  bindings,
		serverURL: serverURL,
		security:  security,
	}
}

type ProduceClient struct {
	bindings  *ServerBindings
	serverURL *url.URL
	security  run.AnySecurityScheme
}

func (p ProduceClient) Publisher(_ context.Context, address string, chb *ChannelBindings, opb *OperationBindings, security run.AnySecurityScheme) (Publisher, error) {
	u := p.serverURL
	// Append the address to the server URL path
	if u.Path == "" {
		// url.JoinPath requires a leading slash in empty path to give the correct result
		// otherwise it will return the path as is, e.g. for "foo" it sets path to "foo" instead of "/foo"
		u.Path = "/"
	}
	if address != "" {
		u = u.JoinPath(address)
	}
	s := p.security
	if security != nil {
		s = security
	}
	return NewPublisher(chb, opb, u, s), nil
}
