// Code generated by go-asyncapi tool. DO NOT EDIT.

package http

import (
	"github.com/bdragon300/go-asyncapi/run"
)

import (
	"context"
	"fmt"
	stdHTTP "net/http"
	"net/url"
)

func NewPublisher(chb *ChannelBindings, opb *OperationBindings, channelURL *url.URL, sec run.AnySecurityScheme) *PublishChannel {
	return &PublishChannel{
		Client:            stdHTTP.DefaultClient,
		channelURL:        channelURL,
		channelBindings:   chb,
		operationBindings: opb,
		security:          sec,
	}
}

type PublishChannel struct {
	Client            *stdHTTP.Client
	channelURL        *url.URL
	channelBindings   *ChannelBindings
	operationBindings *OperationBindings
	security          run.AnySecurityScheme
}

type ImplementationRecord interface {
	AsStdRecord() *stdHTTP.Request
	// TODO: Bindings?
}

func (p PublishChannel) Send(ctx context.Context, envelopes ...EnvelopeWriter) error {
	method := "GET"
	if p.operationBindings != nil && p.operationBindings.Method != "" {
		method = p.operationBindings.Method
	}

	for i, envelope := range envelopes {
		ir := envelope.(ImplementationRecord)
		req := ir.AsStdRecord().WithContext(ctx)
		if req.URL == nil {
			req.URL = p.channelURL
		}

		req.Method = method
		if p.security != nil {
			if err := p.applySecurity(req); err != nil {
				return fmt.Errorf("envelope #%d: %w", i, err)
			}
		}
		if _, err := p.Client.Do(req); err != nil { // TODO: implement request-response interface in channels
			return fmt.Errorf("envelope #%d: %w", i, err)
		}
	}
	return nil
}

func (p PublishChannel) applySecurity(req *stdHTTP.Request) error {
	u := req.URL

	switch v := p.security.(type) {
	case run.UserPasswordSecurity:
		u.User = url.UserPassword(v.UserPassword())
	case run.APIKeySecurity:
		key := v.APIKey()
		switch v.In() {
		case "user":
			u.User = url.User(key)
		case "password":
			if u.User != nil {
				username := u.User.Username()
				u.User = url.UserPassword(username, key)
			} else {
				u.User = url.UserPassword("", key)
			}
		default:
			return fmt.Errorf("unsupported 'in' for apiKey security scheme: %s", v.In())
		}
	default:
		return fmt.Errorf("unsupported security scheme: %v", p.security.AuthType())
	}

	req.URL = u
	return nil
}

func (p PublishChannel) Close() error {
	return nil
}
