// Code generated by go-asyncapi tool. DO NOT EDIT.

package http

import (
	"github.com/bdragon300/go-asyncapi/run"
)

import (
	"context"
)

type SubscribeChannel struct {
	channelBindings   *ChannelBindings
	operationBindings *OperationBindings
	security          run.AnySecurityScheme
	callbacks         *run.Ring[subscriberFunc]
}

func (s *SubscribeChannel) Receive(ctx context.Context, cb func(envelope EnvelopeReader)) error {
	element := s.callbacks.Append(cb)
	defer func() {
		s.callbacks.Remove(element)
	}()

	<-ctx.Done()
	return ctx.Err()
}

func (s *SubscribeChannel) Close() error {
	return nil
}
