# This file contains all available configuration options
# with their default values.
# Config file reference: https://golangci-lint.run/usage/configuration/#config-file
# Linters list: https://golangci-lint.run/usage/linters

run:
  timeout: 5m
  modules-download-mode: readonly
  skip-dirs:
    - pkg/run/3rdparty

linters:
  enable:
    - gofumpt
    - revive
    - gocritic
    - govet
    - staticcheck
    - unused
    - errname
linters-settings:
  govet:
    disable:
      - composites

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
