# This file contains all available configuration options
# with their default values.
# Config file reference: https://golangci-lint.run/usage/configuration/#config-file
# Linters list: https://golangci-lint.run/usage/linters

version: "2"
run:
  modules-download-mode: readonly
linters:
  enable:
    - errname
    - gocritic
    - revive
  settings:
    govet:
      disable:
        - composites
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - text: "avoid meaningless package names"
        linters:
          - revive
    paths:
      - run/3rdparty
      - tmp
      - implementations_go
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofumpt
  exclusions:
    generated: lax
    paths:
      - run/3rdparty
      - tmp
      - implementations_go
