// Code generated by go-asyncapi tool. DO NOT EDIT.

package schemas

type EchoResponse struct {
	// Type--The type of the message.
	Type    string      `json:"type"`
	Message EchoRequest `json:"message"`
}
