// Code generated by go-asyncapi tool. DO NOT EDIT.

package messages

import (
	"encoding/json"
	"github.com/bdragon300/go-asyncapi/run"
	"github.com/bdragon300/go-asyncapi/run/http"
	"http-server/asyncapi/schemas"
	"io"
)

// ServerResponseOut-- (Outbound Message)
type ServerResponseOut struct {
	Payload schemas.EchoResponse
	Headers map[string]any
}

func (m *ServerResponseOut) WithPayload(payload schemas.EchoResponse) *ServerResponseOut {
	m.Payload = payload
	return m
}

func (m *ServerResponseOut) WithHeaders(headers map[string]any) *ServerResponseOut {
	m.Headers = headers
	return m
}

type ServerResponseSender interface {
	Payload() schemas.EchoResponse
	Headers() map[string]any
}
type ServerResponseReceiver interface {
	WithPayload(payload schemas.EchoResponse) *ServerResponseOut
	WithHeaders(headers map[string]any) *ServerResponseOut
}

// ServerResponseIn-- (Inbound Message)
type ServerResponseIn struct {
	payload schemas.EchoResponse
	headers map[string]any
}

func (m *ServerResponseIn) Payload() schemas.EchoResponse {
	return m.payload
}

func (m *ServerResponseIn) Headers() map[string]any {
	return m.headers
}

func (m *ServerResponseOut) MarshalEchoChannelHTTP(envelope http.EnvelopeWriter) error {
	return m.MarshalEnvelopeHTTP(envelope)
}

func (m *ServerResponseOut) MarshalEnvelopeHTTP(envelope http.EnvelopeWriter) error {
	if err := m.MarshalHTTP(envelope); err != nil {
		return err
	}
	envelope.SetContentType("application/json")
	envelope.SetHeaders(run.Headers(m.Headers))
	return nil
}

func (m *ServerResponseOut) MarshalHTTP(w io.Writer) error {

	// Default encoder
	enc := json.NewEncoder(w)
	if err := enc.Encode(m.Payload); err != nil {
		return err
	}
	return nil
}

func (m *ServerResponseIn) UnmarshalEchoChannelHTTP(envelope http.EnvelopeReader) error {
	return m.UnmarshalEnvelopeHTTP(envelope)
}

func (m *ServerResponseIn) UnmarshalEnvelopeHTTP(envelope http.EnvelopeReader) error {
	if err := m.UnmarshalHTTP(envelope); err != nil {
		return err
	}
	m.headers = map[string]any(envelope.Headers())
	return nil
}

func (m *ServerResponseIn) UnmarshalHTTP(r io.Reader) error {

	// Default decoder
	dec := json.NewDecoder(r)
	if err := dec.Decode(&m.payload); err != nil {
		return err
	}
	return nil
}
