package doc

import (
	"bufio"
	"bytes"
	"fmt"
	"hash/crc64"
	"io"
	"os"
	"path"
	"strings"

	"github.com/bdragon300/go-asyncapi/cmd/go-asyncapi/common"
	"github.com/bdragon300/go-asyncapi/internal/jsonpointer"
	"github.com/bdragon300/go-asyncapi/internal/log"
	"github.com/bdragon300/go-asyncapi/internal/types"
	"github.com/bdragon300/go-asyncapi/internal/utils"
	"github.com/samber/lo"
	"golang.org/x/term"
	"gopkg.in/yaml.v3"
)

const (
	defaultStdoutWidth              = 80
	sideBySideColumnSeparator       = " | "
	sideBySideLineNumberPrefixWidth = 6
)

type MergeCmd struct {
	Documents        []string                           `arg:"positional,required" help:"AsyncAPI document file or URL" placeholder:"FILE"`
	Output           string                             `arg:"--output,-o" help:"Output file path. By default, the file name is autogenerated" placeholder:"FILE"`
	Strategy         common2.ToolConfigDocMergeStrategy `arg:"--strategy,-s" help:"Strategy to automatically resolve name conflicts. Possible values: rename, ignore, overwrite" placeholder:"STRATEGY"`
	DisableRewriting bool                               `arg:"--disable-rewriting" help:"Do not rewrite $refs"`
}

func cliMerge(cmd *MergeCmd, cmdConfig common2.ToolConfig) error {
	logger := log.GetLogger("")
	if len(cmd.Documents) < 2 {
		return fmt.Errorf("%w: expected two or more documents", common2.ErrWrongCliArgs)
	}

	outputPath := cmdConfig.Doc.Merge.OutputFile
	if outputPath == "" {
		// Append a checksum of document arguments to generate a unique output file name per combination of input documents
		b := lo.FlatMap(cmd.Documents, func(doc string, _ int) []byte { return append([]byte(doc), 0) })
		sum := crc64.Checksum(b, crc64.MakeTable(crc64.ECMA))
		outputPath = fmt.Sprintf("merged_%s_%x.%s", strings.TrimSuffix(cmd.Documents[0], path.Ext(cmd.Documents[0])), sum, cmdConfig.Doc.Format)
	}
	outputDoc, err := jsonpointer.Parse(outputPath)
	if err != nil {
		return fmt.Errorf("parse output path as url: %w", err)
	}
	if outputDoc.URI != nil {
		return fmt.Errorf("writing to documents by URL is not supported, please provide a file path")
	}

	locator := common2.GetLocator(cmdConfig)
	outputContents := newDocumentTree(outputDoc)
	var changeLog []changeLogEntry
	for _, doc := range cmd.Documents {
		docURL, err := jsonpointer.Parse(doc)
		if err != nil {
			return fmt.Errorf("parse document url %q: %w", doc, err)
		}

		contents, err := loadDocument(docURL, locator)
		if err != nil {
			return fmt.Errorf("load document %q: %w", docURL, err)
		}

		logger.Debug("Merging documents", "destination", outputDoc, "source", contents.OriginDocument())
		var changes []changeLogEntry
		if outputContents, changes, err = mergeDocuments(contents, outputContents, cmdConfig); err != nil {
			return fmt.Errorf("merge document %q: %w", docURL, err)
		}
		changeLog = append(changeLog, changes...)
	}

	if !cmdConfig.Doc.Merge.DisableRewriting {
		logger.Debug("Documents merged, rewriting the $refs")
		rewriteRefs(outputContents, locator, changeLog)
	}

	logger.Info("Writing output file", "file", outputPath)
	outputBuf := bytes.NewBuffer(nil)
	enc, err := getDocumentEncoder(outputBuf, cmdConfig)
	if err != nil {
		return fmt.Errorf("get encoder: %w", err)
	}

	if err = enc.Encode(outputContents); err != nil {
		return fmt.Errorf("marshal output document to yaml: %w", err)
	}
	if err = os.WriteFile(outputPath, outputBuf.Bytes(), 0o644); err != nil {
		return fmt.Errorf("write output file %q: %w", outputPath, err)
	}

	return nil
}

func mergeDocuments(sourceDoc, destDoc *documentTree, cmdConfig common2.ToolConfig) (*documentTree, []changeLogEntry, error) {
	logger := log.GetLogger("")
	if destDoc == nil || sourceDoc == nil {
		panic("destDoc and sourceDoc should not be nil, this is a bug")
	}
	if destDoc.IsZero() {
		return sourceDoc, nil, nil // Keep the original node order if destDoc is empty
	}

	changeLog := relocateEssentialNodes(sourceDoc, destDoc)

	for sMap, dMap := range utils.ZipLongest2(sourceDoc.MergeableMaps(), destDoc.MergeableMaps()) {
		switch {
		case sMap == nil:
			continue // Source is empty, nothing to merge
		case sMap.Kind() != types.RawNodeKindObject:
			return nil, nil, fmt.Errorf("expected an object on path %q in document %q", path.Join(sMap.Path()...), sourceDoc.OriginDocument())
		case sMap.Len() == 0:
			logger.Trace("Source node is empty, skipping", "path", sMap.Path())
			continue
		}

		logger.Debug("Merging nodes", "source", sourceDoc.OriginDocument().Join(sMap.Path()...), "destination", destDoc.OriginDocument().Join(sMap.Path()...))
		switch {
		case dMap == nil:
			logger.Info("Relocating objects", "path", strings.Join(append(sMap.Path(), "*"), "."), "action", "move")
			if err := destDoc.SetNodeByPath(sMap); err != nil {
				return nil, nil, fmt.Errorf("copy object on path %q to document %q: %w", path.Join(sMap.Path()...), destDoc.OriginDocument(), err)
			}
			for _, sNode := range sMap.Entries() {
				changeLog = append(changeLog, changeLogEntry{From: lo.ToPtr(sourceDoc.OriginDocument().Join(sNode.Path()...)), To: lo.ToPtr(destDoc.OriginDocument().Join(sNode.Path()...)), Move: true})
			}
			continue
		case dMap.Kind() != types.RawNodeKindObject:
			return nil, nil, fmt.Errorf("expected an object on path %q in document %q", path.Join(dMap.Path()...), destDoc.OriginDocument())
		}

		for _, sNode := range sMap.Entries() {
			logger.Info("Relocating object", "path", strings.Join(sNode.Path(), "."), "action", "move")
			change, err := copyNode(sNode, dMap, destDoc.OriginDocument(), sourceDoc.OriginDocument(), cmdConfig)
			if err != nil {
				return nil, nil, fmt.Errorf("merge maps %v: %w", path.Join(dMap.Path()...), err)
			}
			if change != nil {
				change.Move = true // All changes are treated as moves for merge operation
				changeLog = append(changeLog, *change)
			}
		}
	}

	return destDoc, changeLog, nil
}

func copyNode(sNode, dMap *types.RawNode, dDoc, sDoc *jsonpointer.JSONPointer, cmdConfig common2.ToolConfig) (*changeLogEntry, error) {
	logger := log.GetLogger("")

	nodeKey := sNode.Path()[len(sNode.Path())-1]
	dNode, conflict := dMap.Get(nodeKey)
	if !conflict {
		logger.Trace("--> Copying object to destination", "destination", dDoc.Join(dMap.Path()...))
		dMap.Set(nodeKey, sNode)
		return &changeLogEntry{
			From: lo.ToPtr(sDoc.Join(sNode.Path()...)),
			To:   lo.ToPtr(dDoc.Join(dMap.Path()...).Join(nodeKey)),
			Move: false,
		}, nil
	}

	logger.Debug("--> Merge conflict", "destination", dDoc.Join(dNode.Path()...), "source", sDoc.Join(sNode.Path()...))
	if dNode.Equal(sNode) {
		logger.Debug("---> Auto skipping duplicate")
		// Add a log entry for duplicate object to make sure that $ref to it will also be rewritten
		return &changeLogEntry{From: lo.ToPtr(sDoc.Join(sNode.Path()...)), To: lo.ToPtr(dDoc.Join(dNode.Path()...)), Move: false}, nil
	}

	changeEntry, err := resolveMergeConflict(dMap, dNode, sNode, dDoc, sDoc, cmdConfig)
	if err != nil {
		return nil, fmt.Errorf("resolve merge conflict for key %q: %w", nodeKey, err)
	}

	if changeEntry != nil && changeEntry.To != nil {
		// Apply a change
		dKey := changeEntry.To.Pointer[len(changeEntry.To.Pointer)-1]
		logger.Debug("--> Copying object with renaming", "destination", changeEntry.To)
		dMap.Set(dKey, sNode)
	} else {
		logger.Debug("--> Ignoring object", "source", sDoc.Join(sNode.Path()...))
	}

	return changeEntry, nil
}

func resolveMergeConflict(dMap, dNode, sNode *types.RawNode, dDoc, sDoc *jsonpointer.JSONPointer, cmdConfig common2.ToolConfig) (*changeLogEntry, error) {
	logger := log.GetLogger("")

	logMsg := "Auto-resolve conflict"
	strategy := cmdConfig.Doc.Merge.Strategy
	if cmdConfig.Quiet && strategy == "" {
		lo.Must(fmt.Fprint(os.Stderr, "ERROR: Empty conflict resolution strategy in quiet mode, use -s flag to set it explicitly. Use --help flag for help.\n"))
		return nil, fmt.Errorf("empty conflict resolution strategy in quiet mode, use -s flag to set it explicitly")
	}
	if strategy == "" {
		fmt.Printf("Merge conflict! Object %q exists both in %q and %q\n", jsonpointer.PointerString(sNode.Path()...), sDoc.Location(), dDoc.Location())
		answers := map[string]common2.ToolConfigDocMergeStrategy{
			"i": common2.ToolConfigDocMergeStrategyIgnore,
			"o": common2.ToolConfigDocMergeStrategyOverwrite,
			"r": common2.ToolConfigDocMergeStrategyRename,
			"":  common2.ToolConfigDocMergeStrategyRename,
		}

		for {
			fmt.Print("Choose option: show (d)iff/(i)gnore/(o)verwrite/(r)ename: [d/i/o/R]: ")
			var choice string
			inp := bufio.NewScanner(os.Stdin)
			if !inp.Scan() {
				return nil, fmt.Errorf("read user choice: %w", inp.Err())
			}
			choice = inp.Text()
			var ok bool
			if strategy, ok = answers[strings.ToLower(choice)]; ok {
				break
			}
			if strings.ToLower(choice) != "d" {
				logger.Error("Invalid input, try again")
				continue
			}

			// Print side-by-side diff in YAML format
			headers := []string{
				fmt.Sprintf("Source: %s", sDoc.Location()),
				fmt.Sprintf("Destination: %s", dDoc.Location()),
			}
			columns := []io.Reader{
				strings.NewReader(formatDiffContent(headers[0], sNode, cmdConfig.Doc.Indent)),
				strings.NewReader(formatDiffContent(headers[1], dNode, cmdConfig.Doc.Indent)),
			}

			termWidth := getTerminalWidth()
			logger.Trace("Terminal width", "width", termWidth)
			colOutput, err := utils.ArrangeInColumns(columns, termWidth-sideBySideLineNumberPrefixWidth, sideBySideColumnSeparator)
			if err != nil {
				return nil, fmt.Errorf("format diff view: %w", err)
			}
			fmt.Print(utils.ReadAllWithLineNumbers(strings.NewReader(colOutput), 2, sideBySideLineNumberPrefixWidth))
		}

		logMsg = "Conflict resolved by user"
	}

	switch strategy {
	case common2.ToolConfigDocMergeStrategyIgnore:
		logger.Info(logMsg, "action", "ignore", "source", sNode)
		return nil, nil
	case common2.ToolConfigDocMergeStrategyOverwrite:
		logger.Info(logMsg, "action", "overwrite", "destination", dNode, "source", sNode)
		return &changeLogEntry{From: lo.ToPtr(sDoc.Join(sNode.Path()...)), To: lo.ToPtr(dDoc.Join(dNode.Path()...)), Move: true}, nil
	case common2.ToolConfigDocMergeStrategyRename:
		k := sNode.Path()[len(sNode.Path())-1]
		for i := 1; ; i++ {
			key := fmt.Sprintf("%s%d", k, i)
			if _, exists := dMap.Get(key); !exists {
				newPath := append(dNode.Path()[:len(dNode.Path())-1], key) // nolint:gocritic
				logger.Info(logMsg, "action", "rename", "destination", dDoc.Join(key), "source", sDoc)
				return &changeLogEntry{From: lo.ToPtr(sDoc.Join(sNode.Path()...)), To: lo.ToPtr(dDoc.Join(newPath...)), Move: true}, nil
			}
		}
	}

	panic(fmt.Sprintf("unknown conflict resolution strategy: %q", strategy))
}

func formatDiffContent(header string, contents *types.RawNode, indentWidth int) string {
	var indentLvl int
	var b strings.Builder

	b.WriteString(header)
	b.WriteString("\n\n")
	for _, p := range contents.Path() {
		b.WriteString(strings.Repeat(" ", indentWidth*indentLvl))
		b.WriteString(p)
		b.WriteString(":\n")
		indentLvl++
	}

	buf := bytes.NewBuffer(nil)
	enc := yaml.NewEncoder(buf)
	enc.SetIndent(indentWidth)
	if err := enc.Encode(contents); err != nil {
		panic(fmt.Errorf("marshal diff content to yaml: %w", err))
	}

	lines := strings.Split(buf.String(), "\n")
	for _, line := range lines {
		b.WriteString(strings.Repeat(" ", indentWidth*indentLvl))
		b.WriteString(line)
		b.WriteString("\n")
	}

	return b.String()
}

func getTerminalWidth() int {
	if term.IsTerminal(int(os.Stdout.Fd())) {
		width, _, err := term.GetSize(int(os.Stdout.Fd()))
		if err != nil {
			panic(fmt.Errorf("get terminal size: %w", err))
		}
		return width
	}
	return defaultStdoutWidth
}
