package doc

import (
	"bufio"
	"bytes"
	"encoding/json"
	"fmt"
	"hash/crc64"
	"io"
	"os"
	"path"
	"path/filepath"
	"strings"

	"github.com/bdragon300/go-asyncapi/cmd/go-asyncapi/common"
	"github.com/bdragon300/go-asyncapi/internal/compiler"
	"github.com/bdragon300/go-asyncapi/internal/jsonpointer"
	"github.com/bdragon300/go-asyncapi/internal/log"
	"github.com/bdragon300/go-asyncapi/internal/types"
	"github.com/bdragon300/go-asyncapi/internal/utils"
	"github.com/samber/lo"
	"golang.org/x/term"
	"gopkg.in/yaml.v3"
)

const (
	defaultStdoutWidth              = 80
	sideBySideColumnSeparator       = " | "
	sideBySideLineNumberPrefixWidth = 6
)

type MergeCmd struct {
	Documents        []string                           `arg:"positional,required" help:"AsyncAPI document file or URL" placeholder:"FILE"`
	Output           string                             `arg:"--output,-o" help:"Output file path. By default, the file name is autogenerated" placeholder:"FILE"`
	Strategy         common2.ToolConfigDocMergeStrategy `arg:"--strategy,-s" help:"Strategy to automatically resolve name conflicts. Possible values: rename, ignore, overwrite" placeholder:"STRATEGY"`
	DisableRewriting bool                               `arg:"--disable-rewriting" help:"Do not rewrite $refs"`
}

func cliMerge(cmd *MergeCmd, cmdConfig common2.ToolConfig) error {
	logger := log.GetLogger("")
	if len(cmd.Documents) < 2 {
		return fmt.Errorf("%w: expected two or more documents", common2.ErrWrongCliArgs)
	}

	outputBuf := bytes.NewBuffer(nil)
	var enc anyEncoder
	switch cmdConfig.Doc.Format {
	case "json":
		logger.Debug("Using JSON output format", "indent", cmdConfig.Doc.Indent)
		e := json.NewEncoder(outputBuf)
		e.SetIndent("", strings.Repeat(" ", cmdConfig.Doc.Indent))
		enc = e
	case "yaml":
		logger.Debug("Using YAML output format", "indent", cmdConfig.Doc.Indent)
		e := yaml.NewEncoder(outputBuf)
		e.SetIndent(cmdConfig.Doc.Indent)
		enc = e
	default:
		return fmt.Errorf("%w: unknown output format %q", common2.ErrWrongCliArgs, cmdConfig.Doc.Format)
	}

	outputPath := cmdConfig.Doc.Merge.OutputFile
	if outputPath == "" {
		// Append a checksum of document arguments to generate a unique output file name per combination of input documents
		b := lo.FlatMap(cmd.Documents, func(doc string, _ int) []byte { return append([]byte(doc), 0) })
		sum := crc64.Checksum(b, crc64.MakeTable(crc64.ECMA))
		outputPath = fmt.Sprintf("merged_%s_%x.%s", strings.TrimSuffix(cmd.Documents[0], path.Ext(cmd.Documents[0])), sum, cmdConfig.Doc.Format)
	}
	outputDoc, err := jsonpointer.Parse(outputPath)
	if err != nil {
		return fmt.Errorf("parse output path as url: %w", err)
	}
	if outputDoc.URI != nil {
		return fmt.Errorf("writing to documents by URL is not supported, please provide a file path")
	}

	locator := common2.GetLocator(cmdConfig)
	var outputContents *documentTree
	var changeLog []changeLogEntry
	for _, doc := range cmd.Documents {
		docURL, err := jsonpointer.Parse(doc)
		if err != nil {
			return fmt.Errorf("parse document url %q: %w", doc, err)
		}

		var contents documentTree
		logger.Debug("Loading document", "url", docURL)
		buf, newDecoder, err := compiler.ReadDocument(docURL, locator, logger)
		if err != nil {
			return fmt.Errorf("read document: %w", err)
		}
		if err = newDecoder(bytes.NewReader(buf)).Decode(&contents); err != nil {
			return fmt.Errorf("decode document: %w", err)
		}
		contents.DocumentURL = *docURL
		for _, ref := range contents.CollectRefs() {
			ref.Meta = docURL // Remember the origin document in ref metadata for later use in $ref rewriting
		}

		logger.Debug("Merging documents", "destination", outputDoc, "source", contents.DocumentURL)
		var changes []changeLogEntry
		if outputContents, changes, err = mergeDocuments(&contents, outputContents, cmdConfig); err != nil {
			return fmt.Errorf("merge document %q: %w", docURL, err)
		}
		outputContents.DocumentURL = *outputDoc
		changeLog = append(changeLog, changes...)
	}

	if !cmdConfig.Doc.Merge.DisableRewriting {
		logger.Debug("Documents merged, rewriting the $refs")
		rewriteRefs(outputContents, locator, changeLog)
	}

	logger.Info("Writing output file", "file", outputPath)
	if err = enc.Encode(outputContents); err != nil {
		return fmt.Errorf("marshal output document to yaml: %w", err)
	}
	if err = os.WriteFile(outputPath, outputBuf.Bytes(), 0o644); err != nil {
		return fmt.Errorf("write output file %q: %w", outputPath, err)
	}

	return nil
}

func mergeDocuments(sourceDoc, destDoc *documentTree, cmdConfig common2.ToolConfig) (*documentTree, []changeLogEntry, error) {
	logger := log.GetLogger("")
	if destDoc == nil {
		return sourceDoc, nil, nil
	}
	if sourceDoc == nil {
		return destDoc, nil, nil
	}

	var changeLog []changeLogEntry
	for sMap, dMap := range utils.ZipLongest2(sourceDoc.MergeableMaps(), destDoc.MergeableMaps()) {
		switch {
		case sMap == nil:
			continue // Source is empty, nothing to merge
		case sMap.Kind() != types.RawNodeKindObject:
			return nil, nil, fmt.Errorf("expected an object on path %q in document %q", path.Join(sMap.Path()...), sourceDoc.DocumentURL)
		case sMap.Len() == 0:
			logger.Trace("Source node is empty, skipping", "path", sMap.Path())
			continue
		}

		logger.Debug("Merging nodes", "source", sourceDoc.DocumentURL.Join(sMap.Path()...), "destination", destDoc.DocumentURL.Join(sMap.Path()...))
		switch {
		case dMap == nil:
			logger.Debug("-> Destination is empty, copying all objects", "path", sMap.Path())
			destDoc.Set(sMap.Path(), sMap)
			for _, sNode := range sMap.Entries() {
				changeLog = append(changeLog, changeLogEntry{Source: lo.ToPtr(sourceDoc.DocumentURL.Join(sNode.Path()...)), Destination: lo.ToPtr(destDoc.DocumentURL.Join(sNode.Path()...)), Move: true})
			}
			continue
		case dMap.Kind() != types.RawNodeKindObject:
			return nil, nil, fmt.Errorf("expected an object on path %q in document %q", path.Join(dMap.Path()...), destDoc.DocumentURL)
		}

		for sKey, sNode := range sMap.Entries() {
			logger.Debug("-> Copying object", "key", sKey, "path", sNode.Path())
			change, err := copyNode(sNode, dMap, destDoc.DocumentURL, sourceDoc.DocumentURL, cmdConfig)
			if err != nil {
				return nil, nil, fmt.Errorf("merge maps %v: %w", path.Join(dMap.Path()...), err)
			}
			if change != nil {
				change.Move = true // All changes are treated as moves for merge operation
				changeLog = append(changeLog, *change)
			}
		}
	}

	return destDoc, changeLog, nil
}

func copyNode(sNode, dMap *types.RawNode, dDoc, sDoc jsonpointer.JSONPointer, cmdConfig common2.ToolConfig) (*changeLogEntry, error) {
	logger := log.GetLogger("")

	nodeKey := sNode.Path()[len(sNode.Path())-1]
	dNode, conflict := dMap.Get(nodeKey)
	if !conflict {
		logger.Trace("--> Copying object to destination", "destination", dDoc.Join(dNode.Path()...))
		dMap.Set(nodeKey, sNode)
		return &changeLogEntry{Source: lo.ToPtr(sDoc.Join(sNode.Path()...)), Destination: lo.ToPtr(dDoc.Join(dNode.Path()...)), Move: false}, nil
	}

	logger.Debug("--> Merge conflict", "destination", dDoc.Join(dNode.Path()...), "source", sDoc.Join(sNode.Path()...))
	if dNode.Equal(sNode) {
		logger.Debug("---> Auto skipping duplicate")
		// Add a log entry for duplicate object to make sure that $ref to it will also be rewritten
		return &changeLogEntry{Source: lo.ToPtr(sDoc.Join(sNode.Path()...)), Destination: lo.ToPtr(dDoc.Join(dNode.Path()...)), Move: false}, nil
	}

	changeEntry, err := resolveMergeConflict(dNode, sNode, dDoc, sDoc, cmdConfig)
	if err != nil {
		return nil, fmt.Errorf("resolve merge conflict for key %q: %w", nodeKey, err)
	}

	if changeEntry != nil && changeEntry.Destination != nil {
		// Apply a change
		dKey := changeEntry.Destination.Pointer[len(changeEntry.Destination.Pointer)-1]
		logger.Debug("--> Copying object with renaming", "destination", changeEntry.Destination)
		dMap.Set(dKey, sNode)
	} else {
		logger.Debug("--> Ignoring object", "source", sDoc.Join(sNode.Path()...))
	}

	return changeEntry, nil
}

func resolveMergeConflict(dMap, sMap *types.RawNode, dPath, sPath jsonpointer.JSONPointer, cmdConfig common2.ToolConfig) (*changeLogEntry, error) {
	logger := log.GetLogger("")

	logMsg := "Auto-resolve conflict"
	strategy := cmdConfig.Doc.Merge.Strategy
	if cmdConfig.Quiet && strategy == "" {
		lo.Must(fmt.Fprint(os.Stderr, "ERROR: Empty conflict resolution strategy in quiet mode, use -s flag to set it explicitly. Use --help flag for help.\n"))
		return nil, fmt.Errorf("empty conflict resolution strategy in quiet mode, use -s flag to set it explicitly")
	}
	if strategy == "" {
		fmt.Printf("Merge conflict! Object %q exists both in %q and %q\n", sPath.PointerString(), sPath.Location(), dPath.Location())
		answers := map[string]common2.ToolConfigDocMergeStrategy{
			"i": common2.ToolConfigDocMergeStrategyIgnore,
			"o": common2.ToolConfigDocMergeStrategyOverwrite,
			"r": common2.ToolConfigDocMergeStrategyRename,
			"":  common2.ToolConfigDocMergeStrategyRename,
		}

		for {
			fmt.Print("Choose option: show (d)iff/(i)gnore/(o)verwrite/(r)ename: [d/i/o/R]: ")
			var choice string
			inp := bufio.NewScanner(os.Stdin)
			if !inp.Scan() {
				return nil, fmt.Errorf("read user choice: %w", inp.Err())
			}
			choice = inp.Text()
			var ok bool
			if strategy, ok = answers[strings.ToLower(choice)]; ok {
				break
			}
			if strings.ToLower(choice) != "d" {
				logger.Error("Invalid input, try again")
				continue
			}

			// Print side-by-side diff in YAML format
			headers := []string{
				fmt.Sprintf("Source: %s", sPath.Location()),
				fmt.Sprintf("Destination: %s", dPath.Location()),
			}
			columns := []io.Reader{
				strings.NewReader(formatDiffContent(headers[0], sPath.Pointer, sMap, cmdConfig.Doc.Indent)),
				strings.NewReader(formatDiffContent(headers[1], dPath.Pointer, dMap, cmdConfig.Doc.Indent)),
			}

			termWidth := getTerminalWidth()
			logger.Trace("Terminal width", "width", termWidth)
			colOutput, err := utils.ArrangeInColumns(columns, termWidth-sideBySideLineNumberPrefixWidth, sideBySideColumnSeparator)
			if err != nil {
				return nil, fmt.Errorf("format diff view: %w", err)
			}
			fmt.Print(utils.ReadAllWithLineNumbers(strings.NewReader(colOutput), 2, sideBySideLineNumberPrefixWidth))
		}

		logMsg = "Conflict resolved by user"
	}

	key := sPath.Pointer[len(sPath.Pointer)-1]
	switch strategy {
	case common2.ToolConfigDocMergeStrategyIgnore:
		logger.Info(logMsg, "action", "ignore", "source", sPath)
		return nil, nil
	case common2.ToolConfigDocMergeStrategyOverwrite:
		logger.Info(logMsg, "action", "overwrite", "destination", dPath, "source", sPath)
		return &changeLogEntry{Source: &sPath, Destination: &dPath, Move: true}, nil
	case common2.ToolConfigDocMergeStrategyRename:
		dPath.Pointer = dPath.Pointer[:len(dPath.Pointer)-1]
		for i := 1; ; i++ {
			newKey := fmt.Sprintf("%s%d", key, i)
			if _, exists := dMap.Get(newKey); !exists {
				logger.Info(logMsg, "action", "rename", "destination", dPath.Join(newKey), "source", sPath)
				return &changeLogEntry{Source: &sPath, Destination: lo.ToPtr(dPath.Join(newKey)), Move: true}, nil
			}
		}
	}

	panic(fmt.Sprintf("unknown conflict resolution strategy: %q", strategy))
}

func formatDiffContent(header string, ptr []string, contents *types.RawNode, indentWidth int) string {
	var indentLvl int
	var b strings.Builder

	b.WriteString(header)
	b.WriteString("\n\n")
	for _, p := range ptr {
		b.WriteString(strings.Repeat(" ", indentWidth*indentLvl))
		b.WriteString(p)
		b.WriteString(":\n")
		indentLvl++
	}

	buf := bytes.NewBuffer(nil)
	enc := yaml.NewEncoder(buf)
	enc.SetIndent(indentWidth)
	if err := enc.Encode(contents); err != nil {
		panic(fmt.Errorf("marshal diff content to yaml: %w", err))
	}

	lines := strings.Split(buf.String(), "\n")
	for _, line := range lines {
		b.WriteString(strings.Repeat(" ", indentWidth*indentLvl))
		b.WriteString(line)
		b.WriteString("\n")
	}

	return b.String()
}

func getTerminalWidth() int {
	if term.IsTerminal(int(os.Stdout.Fd())) {
		width, _, err := term.GetSize(int(os.Stdout.Fd()))
		if err != nil {
			panic(fmt.Errorf("get terminal size: %w", err))
		}
		return width
	}
	return defaultStdoutWidth
}

func rewriteRefs(result *documentTree, locator common2.DocumentLocator, changeLog []changeLogEntry) {
	var err error
	logger := log.GetLogger("")

	for _, obj := range result.CollectRefs() {
		logger.Debug("Processing $ref object", "path", obj.Path())
		if obj.Meta == nil {
			logger.Warn("Found a $ref with empty metadata, this is a bug, skipping", "path", obj.Path())
			continue
		}
		originPath := obj.Meta.(*jsonpointer.JSONPointer) // Document path where this $ref was imported from
		// Explicit document path where this $ref pointed to before been imported. For internal $ref, it's the file itself
		referredPath := originPath

		// Extract jsonpointer from value of variant type
		var ref *jsonpointer.JSONPointer
		variant, _ := obj.Get("$ref")
		if variant.Kind() != types.RawNodeKindScalar {
			logger.Error("$ref value kind is expected to be scalar, skipping", "path", obj.Path(), "kind", variant.Kind())
			continue
		} else if s, ok := variant.AsScalar().(string); ok {
			if ref, err = jsonpointer.Parse(s); err != nil {
				logger.Error("Failed to parse $ref, skipping", "path", obj.Path(), "value", s, "error", err)
				continue
			}
		} else {
			logger.Error("$ref value is expected to be string, skipping", "path", obj.Path(), "type", fmt.Sprintf("%T", variant.AsScalar()))
			continue
		}
		logger.Trace("Parsed $ref", "path", variant.Path(), "value", ref, "originDocument", originPath)
		if ref.Location() != "" {
			// Resolve location in external $ref relative to it's origin document location
			if referredPath, err = locator.ResolveURL(originPath, ref); err != nil {
				logger.Error("Failed to resolve $ref, skipping", "path", obj.Path(), "value", ref, "error", err)
				continue
			}
		}

		logger.Debug("Rewriting $ref", "path", variant.Path(), "value", ref, "originDocument", originPath, "referredDocument", referredPath)
		newRef := rewriteRef(ref, referredPath, originPath, result, changeLog)
		if newRef == nil {
			continue
		}

		logger.Debug("Updating $ref", "path", variant.Path(), "old", ref, "new", newRef)
		obj.Set("$ref", types.NewScalarRawNode(variant.Path(), newRef.String()))
	}
}

func rewriteRef(ref, referredPath, originPath *jsonpointer.JSONPointer, result *documentTree, changeLog []changeLogEntry) *jsonpointer.JSONPointer {
	logger := log.GetLogger("")
	newRef := *ref

	var matched bool
	for i := 0; i < len(changeLog) && !matched; i++ {
		change := changeLog[i]
		logger.Trace("-> Checking changelog entry", "entry", change)
		if change.Source == nil || change.Destination == nil {
			continue
		}
		if len(change.Source.Pointer) == 0 || len(change.Destination.Pointer) == 0 || len(ref.Pointer) == 0 {
			continue
		}
		pathSuffix, matchPointers := lo.CutPrefix(ref.Pointer, change.Source.Pointer)
		matched = absLocation(change.Source) == absLocation(referredPath) && matchPointers && absLocation(change.Destination) == absLocation(&result.DocumentURL)
		if !matched {
			logger.Trace("--> No match")
			continue
		}

		if ref.Location() != "" {
			// Object has been moved/copied to result document, so make the $ref internal (i.e. remove location part)
			logger.Debug("-> Erasing location", "location", ref.Location())
			newRef.URI = nil
			newRef.FSPath = ""
		}

		// Rewrite pointer path in $ref if it points to an object (or its nested value) that was renamed during merge
		newRef.Pointer = append(change.Destination.Pointer, pathSuffix...) // nolint:gocritic
		logger.Debug("-> Fixing pointer", "old", ref.PointerString(), "new", newRef.PointerString())
	}

	if matched {
		return &newRef
	}

	// Rewriting the $refs that are not in changelog
	p := referredPath
	pointedToInputDocument := lo.SomeBy(changeLog, func(change changeLogEntry) bool {
		if change.Source == nil || change.Destination == nil {
			return false
		}
		return absLocation(change.Source) == absLocation(referredPath)
	})

	switch {
	case absLocation(originPath) == absLocation(&result.DocumentURL):
		// All $refs that weren't imported
		logger.Debug("-> Not imported from any input document, skipping")
		return nil
	case ref.Location() != "" && absLocation(referredPath) == absLocation(&result.DocumentURL):
		// External $refs, that explicitly pointed to result document
		logger.Debug("-> Erasing location to result document", "location", ref.Location())
		newRef.URI = nil
		newRef.FSPath = ""
	case ref.Location() == "" && result.DocumentURL.URI != nil:
		// Internal $refs that imported from an input document addressed by URL
		logger.Debug("-> Setting $ref location to its origin document", "location", originPath.URI)
		newRef.URI = originPath.URI
	case ref.Location() == "" && result.DocumentURL.FSPath != "":
		// Internal $refs that imported from an input document addressed by file path
		p = originPath
		fallthrough // Add a location part relative to the result document path
	case ref.FSPath != "" && !pointedToInputDocument:
		// Imported external $refs that pointed to a 3rd-party document addressed by file path
		newPath, err := filepath.Rel(path.Dir(absLocation(&result.DocumentURL)), absLocation(p))
		if err != nil {
			logger.Error("Failed to rewrite external location in $ref, leaving it as-is", "value", ref, "error", err)
			return &newRef
		}
		logger.Debug("-> Fixing $ref location to external document", "location", newPath)
		newRef.FSPath = newPath
	case ref.Location() != "" && pointedToInputDocument:
		// External $refs that imported from one input document and pointed to any input document (including the same one)
		logger.Debug("-> Erasing location to one of input documents", "location", ref.Location())
		newRef.URI = nil
		newRef.FSPath = ""
	}

	return &newRef
}
