package doc

import (
	"bufio"
	"bytes"
	"fmt"
	"hash/crc64"
	"io"
	"os"
	"path"
	"path/filepath"
	"strings"

	"github.com/bdragon300/go-asyncapi/cmd/go-asyncapi/common"
	"github.com/bdragon300/go-asyncapi/internal/compiler"
	"github.com/bdragon300/go-asyncapi/internal/jsonpointer"
	"github.com/bdragon300/go-asyncapi/internal/log"
	"github.com/bdragon300/go-asyncapi/internal/types"
	"github.com/bdragon300/go-asyncapi/internal/utils"
	"github.com/samber/lo"
	"golang.org/x/term"
	"gopkg.in/yaml.v3"
)

type MergeCmd struct {
	Documents        []string                           `arg:"positional,required" help:"AsyncAPI document file or URL" placeholder:"FILE"`
	Output           string                             `arg:"--output,-o" help:"Output file path. By default, the file name is autogenerated" placeholder:"FILE"`
	Strategy         common2.ToolConfigDocMergeStrategy `arg:"--strategy,-s" help:"Strategy to automatically resolve name conflicts. Possible values: rename, ignore, overwrite" placeholder:"STRATEGY"`
	DisableRewriting bool                               `arg:"--disable-rewriting" help:"Disable $refs rewriting"`
}

func cliMerge(cmd *MergeCmd, cmdConfig common2.ToolConfig) error {
	logger := log.GetLogger("")
	if len(cmd.Documents) < 2 {
		return fmt.Errorf("%w: expected two or more documents", common2.ErrWrongCliArgs)
	}

	outputPath := cmd.Output
	if outputPath == "" {
		// Append a checksum of document arguments to generate a unique output file name per combination of input documents
		b := lo.FlatMap(cmd.Documents, func(doc string, _ int) []byte { return append([]byte(doc), 0) })
		sum := crc64.Checksum(b, crc64.MakeTable(crc64.ECMA))
		outputPath = fmt.Sprintf("merged_%s_%x.yaml", strings.TrimSuffix(cmd.Documents[0], path.Ext(cmd.Documents[0])), sum)
	}
	outputPtr, err := jsonpointer.Parse(outputPath)
	if err != nil {
		return fmt.Errorf("parse output path as url: %w", err)
	}

	locator := common2.GetLocator(cmdConfig)
	var docURLs []*jsonpointer.JSONPointer
	var resultDocument *documentTree
	var changeLog []changeLogEntry
	for _, doc := range cmd.Documents {
		docURL, err := jsonpointer.Parse(doc)
		if err != nil {
			return fmt.Errorf("parse document url %q: %w", doc, err)
		}
		docURLs = append(docURLs, docURL)

		var contents documentTree
		logger.Debug("Loading document", "url", docURL)
		buf, newDecoder, err := compiler.ReadDocument(docURL, locator, logger)
		if err != nil {
			return fmt.Errorf("read document: %w", err)
		}
		if err = newDecoder(bytes.NewReader(buf)).Decode(&contents); err != nil {
			return fmt.Errorf("decode document: %w", err)
		}
		contents.DocumentURL = *docURL
		for _, ref := range contents.CollectRefs() {
			ref.Meta = docURL // Remember the origin document in ref metadata for later use in $ref rewriting
		}

		logger.Debug("Merging documents", "destination", outputPtr, "source", contents.DocumentURL)
		var changes []changeLogEntry
		if resultDocument, changes, err = mergeDocuments(&contents, resultDocument, cmdConfig); err != nil {
			return fmt.Errorf("merge document %q: %w", docURL, err)
		}
		resultDocument.DocumentURL = *outputPtr
		changeLog = append(changeLog, changes...)
	}

	if !cmdConfig.Doc.Merge.DisableRewriting {
		logger.Debug("Documents merged, rewriting $refs")
		rewriteRefs(resultDocument, docURLs, locator, changeLog)
	}

	logger.Info("Writing output file", "file", outputPath)
	buf := bytes.NewBuffer(nil)
	enc := yaml.NewEncoder(buf)
	enc.SetIndent(cmdConfig.Doc.YAMLIndent)
	if err = enc.Encode(resultDocument); err != nil {
		return fmt.Errorf("marshal output document to yaml: %w", err)
	}
	if err = os.WriteFile(outputPath, buf.Bytes(), 0o644); err != nil {
		return fmt.Errorf("write output file %q: %w", outputPath, err)
	}
	logger.Debug("Writing complete")

	return nil
}

func mergeDocuments(sourceDoc, destDoc *documentTree, cmdConfig common2.ToolConfig) (*documentTree, []changeLogEntry, error) {
	logger := log.GetLogger("")
	if destDoc == nil {
		return sourceDoc, nil, nil
	}
	if sourceDoc == nil {
		return destDoc, nil, nil
	}

	var changeLog []changeLogEntry
	for src, dst := range utils.ZipLongest2(sourceDoc.MergeableNodes(), destDoc.MergeableNodes()) {
		if src == nil || dst == nil {
			continue
		}
		logger.Trace("Merging nodes", "source", src.Path(), "destination", dst.Path())
		switch {
		case src.Kind() != types.RawNodeKindObject:
			return nil, nil, fmt.Errorf("expected an object on path %q in document %q", path.Join(src.Path()...), sourceDoc.DocumentURL)
		case dst.Kind() != types.RawNodeKindObject:
			return nil, nil, fmt.Errorf("expected an object on path %q in document %q", path.Join(dst.Path()...), destDoc.DocumentURL)
		case src.Len() == 0 && dst.Len() == 0:
			logger.Trace("Both nodes are empty, skipping", "source", src.Path(), "destination", dst.Path())
			continue
		}
		changes, err := mergeMaps(dst, src, destDoc.DocumentURL.Join(src.Path()...), sourceDoc.DocumentURL.Join(dst.Path()...), cmdConfig)
		if err != nil {
			return nil, nil, fmt.Errorf("merge maps %v: %w", path.Join(dst.Path()...), err)
		}
		changeLog = append(changeLog, changes...)
	}

	return destDoc, changeLog, nil
}

func mergeMaps(destMap, srcMap *types.RawNode, dest, src jsonpointer.JSONPointer, cmdConfig common2.ToolConfig) ([]changeLogEntry, error) {
	logger := log.GetLogger("")
	var changeLog []changeLogEntry

	for skey, sval := range srcMap.Entries() {
		logger.Trace("Merging key", "key", skey, "path", sval.Path())

		skeystr := skey.(string) // Keys in two maps to merge are expected to be strings
		dval, conflict := destMap.Get(skey)
		if !conflict {
			logger.Trace("Moving object to destination", "key", skeystr, "value", sval)
			destMap.Set(skey, sval)
			changeLog = append(changeLog, changeLogEntry{Source: lo.ToPtr(src.Join(skeystr)), Destination: lo.ToPtr(dest.Join(skeystr))})
			continue
		}

		logger.Debug("Merge conflict", "destination", dest.Join(skeystr), "source", src.Join(skeystr))
		if dval.Equal(sval) {
			logger.Debug("Auto eliminating duplicate", "path", dval.Path())
			// Automatically apply "overwrite" strategy to let all $refs to source object to be overwritten to the destination object
			changeLog = append(changeLog, changeLogEntry{Source: lo.ToPtr(src.Join(skeystr)), Destination: lo.ToPtr(dest.Join(skeystr))})
			continue
		}

		changeEntry, err := resolveMergeConflict(dval, sval, dest.Join(skeystr), src.Join(skeystr), cmdConfig)
		if err != nil {
			return nil, fmt.Errorf("resolve key conflict for key %q: %w", skeystr, err)
		}
		changeLog = append(changeLog, changeEntry)

		// Apply a change
		if changeEntry.Destination == nil || len(changeEntry.Destination.Pointer) == 0 {
			logger.Debug("Ignoring source object", "destination", dest.Join(skeystr), "source", src.Join(skeystr))
			continue
		}
		dKey := changeEntry.Destination.Pointer[len(changeEntry.Destination.Pointer)-1]
		logger.Debug("Moving destination object", "destination", dest.Join(skeystr), "source", src.Join(skeystr), "name", dKey)
		destMap.Set(dKey, sval)
	}

	return changeLog, nil
}

func resolveMergeConflict(dMap, sMap *types.RawNode, dPath, sPath jsonpointer.JSONPointer, cmdConfig common2.ToolConfig) (changeLogEntry, error) {
	logger := log.GetLogger("")

	logMsg := "Auto-resolve conflict"
	strategy := cmdConfig.Doc.Merge.Strategy
	if cmdConfig.Quiet && strategy == "" {
		lo.Must(fmt.Fprint(os.Stderr, "ERROR: Empty conflict resolution strategy in quiet mode, use -s flag to set it explicitly. Use --help flag for help.\n"))
		return changeLogEntry{}, fmt.Errorf("empty conflict resolution strategy in quiet mode, use -s flag to set it explicitly")
	}
	if strategy == "" {
		fmt.Printf("Merge conflict! Object %q exists both in %q and %q\n", sPath.PointerString(), sPath.Location(), dPath.Location())
		answers := map[string]common2.ToolConfigDocMergeStrategy{
			"i": common2.ToolConfigDocMergeStrategyIgnore,
			"o": common2.ToolConfigDocMergeStrategyOverwrite,
			"r": common2.ToolConfigDocMergeStrategyRename,
			"":  common2.ToolConfigDocMergeStrategyRename,
		}

		for {
			fmt.Print("Choose option: show (d)iff/(i)gnore/(o)verwrite/(r)ename: [d/i/o/R]: ")
			var choice string
			inp := bufio.NewScanner(os.Stdin)
			if !inp.Scan() {
				return changeLogEntry{}, fmt.Errorf("read user choice: %w", inp.Err())
			}
			choice = inp.Text()
			var ok bool
			if strategy, ok = answers[strings.ToLower(choice)]; ok {
				break
			}
			if strings.ToLower(choice) != "d" {
				logger.Error("Invalid input, try again")
				continue
			}

			// Print side-by-side diff in YAML format
			headers := []string{
				fmt.Sprintf("Source: %s", sPath.Location()),
				fmt.Sprintf("Destination: %s", dPath.Location()),
			}
			columns := []io.Reader{
				strings.NewReader(formatDiffContent(headers[0], sPath.Pointer, sMap, cmdConfig.Doc.YAMLIndent)),
				strings.NewReader(formatDiffContent(headers[1], dPath.Pointer, dMap, cmdConfig.Doc.YAMLIndent)),
			}

			termWidth := getTerminalWidth()
			logger.Trace("Terminal width", "width", termWidth)
			colOutput, err := utils.ArrangeInColumns(columns, termWidth-sideBySideLineNumberPrefixWidth, sideBySideColumnSeparator)
			if err != nil {
				return changeLogEntry{}, fmt.Errorf("format diff view: %w", err)
			}
			fmt.Print(utils.ReadAllWithLineNumbers(strings.NewReader(colOutput), 2, sideBySideLineNumberPrefixWidth))
		}

		logMsg = "Conflict resolved by user"
	}

	key := sPath.Pointer[len(sPath.Pointer)-1]
	switch strategy {
	case common2.ToolConfigDocMergeStrategyIgnore:
		logger.Info(logMsg, "action", "ignore", "source", sPath)
		return changeLogEntry{Source: &sPath, Destination: nil}, nil
	case common2.ToolConfigDocMergeStrategyOverwrite:
		logger.Info(logMsg, "action", "overwrite", "destination", dPath, "source", sPath)
		return changeLogEntry{Source: &sPath, Destination: &dPath}, nil
	case common2.ToolConfigDocMergeStrategyRename:
		dPath.Pointer = dPath.Pointer[:len(dPath.Pointer)-1]
		for i := 1; ; i++ {
			newKey := fmt.Sprintf("%s%d", key, i)
			if _, exists := dMap.Get(newKey); !exists {
				logger.Info(logMsg, "action", "rename", "destination", dPath.Join(newKey), "source", sPath)
				return changeLogEntry{Source: &sPath, Destination: lo.ToPtr(dPath.Join(newKey))}, nil
			}
		}
	}

	panic(fmt.Sprintf("unknown conflict resolution strategy: %q", strategy))
}

func formatDiffContent(header string, ptr []string, contents *types.RawNode, indentWidth int) string {
	var indentLvl int
	var b strings.Builder

	b.WriteString(header)
	b.WriteString("\n\n")
	for _, p := range ptr {
		b.WriteString(strings.Repeat(" ", indentWidth*indentLvl))
		b.WriteString(p)
		b.WriteString(":\n")
		indentLvl++
	}

	buf := bytes.NewBuffer(nil)
	enc := yaml.NewEncoder(buf)
	enc.SetIndent(indentWidth)
	if err := enc.Encode(contents); err != nil {
		panic(fmt.Errorf("marshal diff content to yaml: %w", err))
	}

	lines := strings.Split(buf.String(), "\n")
	for _, line := range lines {
		b.WriteString(strings.Repeat(" ", indentWidth*indentLvl))
		b.WriteString(line)
		b.WriteString("\n")
	}

	return b.String()
}

func getTerminalWidth() int {
	if term.IsTerminal(int(os.Stdout.Fd())) {
		width, _, err := term.GetSize(int(os.Stdout.Fd()))
		if err != nil {
			panic(fmt.Errorf("get terminal size: %w", err))
		}
		return width
	}
	return defaultStdoutWidth
}

func rewriteRefs(doc *documentTree, sourceDocs []*jsonpointer.JSONPointer, locator common2.DocumentLocator, changeLog []changeLogEntry) {
	logger := log.GetLogger("")
	getAbsLoc := func(p *jsonpointer.JSONPointer) string {
		if p.FSPath != "" {
			return lo.Must(filepath.Abs(p.FSPath))
		}
		return p.Location()
	}

	for _, obj := range doc.CollectRefs() {
		logger.Debug("Processing $ref object", "path", obj.Path())
		if obj.Meta == nil {
			logger.Warn("Found a $ref with empty metadata, this is a bug, skipping", "path", obj.Path())
			continue
		}
		originPath := obj.Meta.(*jsonpointer.JSONPointer) // Document path where this $ref was before the merge
		referredPath := originPath                        // Explicit document path where this $ref pointed to before the merge

		// Extract jsonpointer from value of variant type
		var rawRef string
		variant, _ := obj.Get("$ref")
		if valid := variant.Kind() == types.RawNodeKindScalar; valid {
			if rawRef, valid = variant.AsScalar().(string); !valid {
				logger.Error("$ref value is expected to be string, skipping", "path", obj.Path(), "kind", variant.Kind())
				continue
			}
		}
		ref, err := jsonpointer.Parse(rawRef)
		if err != nil {
			logger.Error("Failed to parse $ref, skipping", "path", obj.Path(), "value", rawRef, "error", err)
			continue
		}
		logger.Trace("Parsed $ref", "path", variant.Path(), "value", ref, "originDocument", originPath)
		newRef := *ref
		changed := false

		if ref.Location() != "" {
			// Resolve relative path in $ref against the origin path
			if referredPath, err = locator.ResolveURL(originPath, ref); err != nil {
				logger.Error("Failed to rewrite $ref, skipping", "path", obj.Path(), "value", rawRef, "error", err)
				continue
			}
			_, found := lo.Find(sourceDocs, func(docURL *jsonpointer.JSONPointer) bool {
				return getAbsLoc(docURL) == getAbsLoc(referredPath)
			})
			if found {
				// Make $ref internal (i.e. remove location) if it points to any of merged documents
				logger.Debug("-> Removing location of merged document", "was", ref.Location())
				newRef.URI = nil
				newRef.FSPath = ""
				changed = true
			} else if newRef.FSPath != "" && doc.DocumentURL.FSPath != "" {
				// Rewrite $ref to 3rd-party file according to new location of merged document
				if p, err := filepath.Rel(path.Dir(getAbsLoc(&doc.DocumentURL)), getAbsLoc(referredPath)); err != nil {
					logger.Error("Failed to rewrite external location in $ref, leave it as-is", "path", obj.Path(), "value", rawRef, "error", err)
				} else {
					logger.Debug("-> Rewriting location to external document", "old", ref.Location(), "new", p)
					newRef.FSPath = p
					changed = true
				}
			}
		}

		// Rewrite pointer path in $ref if it points to an object (or its nested part) that was renamed during merge
		for _, change := range changeLog {
			rest, match := lo.CutPrefix(ref.Pointer, change.Source.Pointer)
			if match && getAbsLoc(referredPath) == getAbsLoc(change.Source) && change.Destination != nil {
				newRef.Pointer = append(change.Destination.Pointer, rest...) // nolint:gocritic
				logger.Debug("-> Rewriting pointer", "old", ref.PointerString(), "new", newRef.PointerString())
				changed = true
				break
			}
		}

		if changed {
			logger.Debug("Updating $ref", "path", variant.Path(), "old", ref, "new", newRef, "originDocument", getAbsLoc(originPath), "referredDocument", getAbsLoc(referredPath))
			obj.Set("$ref", types.NewScalarRawNode(variant.Path(), newRef.String()))
		}
	}
}
