package doc

import (
	"bytes"
	"encoding/json"
	"fmt"
	"hash/crc64"
	"os"
	"path"
	"strings"

	"github.com/bdragon300/go-asyncapi/cmd/go-asyncapi/common"
	"github.com/bdragon300/go-asyncapi/internal/compiler"
	"github.com/bdragon300/go-asyncapi/internal/jsonpointer"
	"github.com/bdragon300/go-asyncapi/internal/log"
	"github.com/bdragon300/go-asyncapi/internal/types"
	"github.com/bdragon300/go-asyncapi/internal/utils"
	"github.com/gobwas/glob"
	"github.com/samber/lo"
	"gopkg.in/yaml.v3"
)

type UnmergeCmd struct {
	Document string `arg:"positional,required" help:"AsyncAPI document file or URL" placeholder:"FILE"`
	// TODO: add url link
	Patterns         []string `arg:"positional" help:"Globbing pattern of the objects to move to output document" placeholder:"PATTERN"`
	DependencyMode   string   `arg:"--mode,-m" help:"Dependency moving mode. Possible values: auto, duplicate, reference" placeholder:"MODE"`
	Copy             bool     `arg:"--copy" help:"Copy matched objects instead of moving, leaving the original document unchanged"`
	Output           string   `arg:"--output,-o" help:"Output file path. By default, the file name is autogenerated" placeholder:"FILE"`
	DisableRewriting bool     `arg:"--disable-rewriting" help:"Do not rewrite $refs"`
}

func cliUnmerge(cmd *UnmergeCmd, cmdConfig common2.ToolConfig) error {
	logger := log.GetLogger("")

	outputBuf := bytes.NewBuffer(nil)
	var enc anyEncoder
	switch cmdConfig.Doc.Format {
	case "json":
		logger.Debug("Using JSON output format", "indent", cmdConfig.Doc.Indent)
		e := json.NewEncoder(outputBuf)
		e.SetIndent("", strings.Repeat(" ", cmdConfig.Doc.Indent))
		enc = e
	case "yaml":
		logger.Debug("Using YAML output format", "indent", cmdConfig.Doc.Indent)
		e := yaml.NewEncoder(outputBuf)
		e.SetIndent(cmdConfig.Doc.Indent)
		enc = e
	default:
		return fmt.Errorf("%w: unknown output format %q", common2.ErrWrongCliArgs, cmdConfig.Doc.Format)
	}

	outputPath := cmd.Output
	if outputPath == "" {
		// Append a checksum of document arguments to generate a unique output file name per combination of input documents
		b := lo.FlatMap(cmd.Patterns, func(doc string, _ int) []byte { return append([]byte(doc), 0) })
		sum := crc64.Checksum(b, crc64.MakeTable(crc64.ECMA))
		outputPath = fmt.Sprintf("unmerged_%s_%x.%s", strings.TrimSuffix(cmd.Document, path.Ext(cmd.Document)), sum, cmdConfig.Doc.Format)
	}
	outputDoc, err := jsonpointer.Parse(outputPath)
	if err != nil {
		return fmt.Errorf("parse output path as url: %w", err)
	}
	if outputDoc.URI != nil {
		return fmt.Errorf("writing to documents by URL is not supported, please provide a file path")
	}

	inputDoc, err := jsonpointer.Parse(cmd.Document)
	if err != nil {
		return fmt.Errorf("parse document url %q: %w", cmd.Document, err)
	}
	if inputDoc.URI != nil {
		return fmt.Errorf("modifying documents by URL is not supported, you can use --copy flag for read-only mode")
	}

	var inputContents documentTree
	logger.Debug("Loading document", "url", inputDoc)
	locator := common2.GetLocator(cmdConfig)
	buf, newDecoder, err := compiler.ReadDocument(inputDoc, locator, logger)
	if err != nil {
		return fmt.Errorf("read document: %w", err)
	}
	if err = newDecoder(bytes.NewReader(buf)).Decode(&inputContents); err != nil {
		return fmt.Errorf("decode document: %w", err)
	}
	inputContents.DocumentURL = *inputDoc

	patterns := lo.Map(cmd.Patterns, func(p string, _ int) glob.Glob {
		g, err := glob.Compile(p)
		if err != nil {
			panic(fmt.Sprintf("invalid glob pattern %q: %v", p, err)) // This should be caught by arg parsing validation
		}
		return g
	})

	outputContents := documentTree{DocumentURL: *outputDoc}
	changeLog, err := unmergeDocument(&inputContents, &outputContents, patterns, cmdConfig)
	if err != nil {
		return fmt.Errorf("unmerge documents: %w", err)
	}

	if !cmdConfig.Doc.Unmerge.DisableRewriting {
		logger.Debug("Document unmerged, rewriting the $refs")
		rewriteRefs(&outputContents, locator, changeLog)
	}

	logger.Info("Writing output file", "file", outputPath)
	if err = enc.Encode(outputContents); err != nil {
		return fmt.Errorf("marshal output document to yaml: %w", err)
	}
	if err = os.WriteFile(outputPath, outputBuf.Bytes(), 0o644); err != nil {
		return fmt.Errorf("write output file %q: %w", outputPath, err)
	}

	return nil
}

func unmergeDocument(sourceDoc, destDoc *documentTree, patterns []glob.Glob, cmdConfig common2.ToolConfig) ([]changeLogEntry, error) {
	logger := log.GetLogger("")
	if sourceDoc == nil || destDoc == nil {
		panic("sourceDoc or destDoc is nil, this is a bug")
	}

	var changeLog []changeLogEntry
	for sMap, dMap := range utils.ZipLongest2(sourceDoc.MergeableMaps(), destDoc.MergeableMaps()) {
		switch {
		case sMap == nil:
			continue // Source is empty, nothing to merge
		case sMap.Kind() != types.RawNodeKindObject:
			return nil, fmt.Errorf("expected an object on path %q in document %q", path.Join(sMap.Path()...), sourceDoc.DocumentURL)
		case sMap.Len() == 0:
			logger.Trace("Source node is empty, skipping", "path", sMap.Path())
			continue
		}

		logger.Debug("Relocating nodes", "source", sourceDoc.DocumentURL.Join(sMap.Path()...), "destination", destDoc.DocumentURL.Join(sMap.Path()...))
		switch {
		case dMap == nil:
			dMap = sMap.CloneZero()
			destDoc.SetByPath(dMap.Path(), dMap)
		case dMap.Kind() != types.RawNodeKindObject:
			return nil, fmt.Errorf("expected an object on path %q in document %q", path.Join(dMap.Path()...), destDoc.DocumentURL)
		}

		for sKey, sNode := range sMap.Entries() {
			nodePath := strings.Join(sNode.Path(), ".")
			logger.Debug("Object", "path", nodePath, "key", sKey, "path", sNode.Path())

			matched := lo.SomeBy(patterns, func(p glob.Glob) bool { return p.Match(nodePath) })
			if !matched {
				logger.Trace("-> No pattern matched, skipping", "path", nodePath)
				continue
			}

			change, err := copyNode(sNode, dMap, destDoc.DocumentURL, sourceDoc.DocumentURL, cmdConfig)
			if err != nil {
				return nil, fmt.Errorf("copy nodes %v: %w", jsonpointer.PointerString(sMap.Path()...), err)
			}
			if change == nil {
				continue
			}

			if !cmdConfig.Doc.Unmerge.Copy {
				if change.Source != nil && change.Destination != nil {
					logger.Trace("-> Removing original object", "source", change.Source.String())
					sourceDoc.DeleteByPath(change.Source.Pointer)
					change.Move = true // TODO: depends on the dependency mode
				}
			}
			changeLog = append(changeLog, *change)
		}
	}

	return changeLog, nil
}
