package doc

import (
	"bufio"
	"bytes"
	"errors"
	"fmt"
	"hash/crc64"
	"io"
	"os"
	"path"
	"strconv"
	"strings"

	"github.com/bdragon300/go-asyncapi/cmd/go-asyncapi/common"
	"github.com/bdragon300/go-asyncapi/internal/jsonpointer"
	"github.com/bdragon300/go-asyncapi/internal/log"
	"github.com/bdragon300/go-asyncapi/internal/types"
	"github.com/bdragon300/go-asyncapi/internal/utils"
	"github.com/gobwas/glob"
	"github.com/samber/lo"
)

type UnmergeCmd struct {
	Document string `arg:"positional,required" help:"AsyncAPI document file or URL" placeholder:"FILE"`
	// TODO: add docs url link
	Patterns         []string `arg:"positional" help:"Globbing pattern to select objects to relocate" placeholder:"PATTERN"`
	UnmergeTo        string   `arg:"--unmerge-to,-t" help:"File where to relocate the objects to. Autogenerated by default." placeholder:"FILE"`
	Output           string   `arg:"--output,-o" help:"File where to write the modified original document. By default, the original document is modified in-place" placeholder:"FILE"`
	IncludeDeps      string   `arg:"--include-deps,-i" help:"Which dependencies of selected objects must be relocated as well. Possible values: none, orphaned-deps, all" placeholder:"MODE"`
	DuplicateObjects string   `arg:"--duplicate-objects,-d" help:"Which objects to duplicate instead of moving during relocating. Possible values: none, all-deps, shared-deps, all" placeholder:"MODE"`
	DisableRewriting bool     `arg:"--disable-rewriting" help:"Do not rewrite $refs"`
	NoInteractive    bool     `arg:"--no-interactive" help:"Disable interactive mode and require patterns to be provided"`
}

func cliUnmerge(cmd *UnmergeCmd, cmdConfig common2.ToolConfig) error {
	logger := log.GetLogger("")

	unmergedPath := cmdConfig.Doc.Unmerge.UnmergeTo
	if unmergedPath == "" {
		// Append a checksum of document arguments to generate a unique output file name per combination of input documents
		b := lo.FlatMap(cmd.Patterns, func(doc string, _ int) []byte { return append([]byte(doc), 0) })
		sum := crc64.Checksum(b, crc64.MakeTable(crc64.ECMA))
		unmergedPath = fmt.Sprintf("unmerged_%s_%x.%s", strings.TrimSuffix(cmd.Document, path.Ext(cmd.Document)), sum, cmdConfig.Doc.Format)
	}
	unmergedDoc, err := jsonpointer.Parse(unmergedPath)
	if err != nil {
		return fmt.Errorf("parse output path as url: %w", err)
	}
	if unmergedDoc.URI != nil {
		return fmt.Errorf("writing to documents by URL is not supported, please provide a file path")
	}

	inputDoc, err := jsonpointer.Parse(cmd.Document)
	if err != nil {
		return fmt.Errorf("parse document url %q: %w", cmd.Document, err)
	}
	if inputDoc.URI != nil {
		return fmt.Errorf("modifying documents by URL is not supported, use --output option to specify a file to write the modified content")
	}

	logger.Debug("Loading document", "url", inputDoc)
	locator := common2.GetLocator(cmdConfig)
	inputContents, err := loadDocument(inputDoc, locator)
	if err != nil {
		return fmt.Errorf("load document: %w", err)
	}

	patterns := lo.Map(cmd.Patterns, func(p string, _ int) glob.Glob {
		g, err := glob.Compile(p)
		if err != nil {
			panic(fmt.Sprintf("invalid glob pattern %q: %v", p, err)) // This should be caught by arg parsing validation
		}
		return g
	})
	var selections []*types.RawNode
	if len(patterns) == 0 {
		// Interactive mode
		if cmdConfig.Doc.Unmerge.NoInteractive || cmdConfig.Quiet {
			return fmt.Errorf("%w: patterns must be provided in non-interactive mode", common2.ErrWrongCliArgs)
		}

		logger.Debug("No patterns provided, switching to interactive mode")
		mergeableNodes := lo.FlatMap(inputContents.MergeableMaps(), func(m *types.RawNode, _ int) []*types.RawNode {
			if m == nil || m.Kind() != types.RawNodeKindObject {
				return nil
			}
			var res []*types.RawNode
			for _, e := range m.Entries() {
				res = append(res, e)
			}
			return res
		})
		selectedIndexes, err := promptSelectMergeableObjects(inputDoc, unmergedDoc, mergeableNodes, os.Stdout, os.Stdin)
		if err != nil {
			return fmt.Errorf("user prompt: %w", err)
		}
		selections = lo.Map(selectedIndexes, func(i int, _ int) *types.RawNode { return mergeableNodes[i] })
	}

	unmergedContents := newDocumentTree(unmergedDoc)
	if _, err = os.Stat(unmergedPath); err == nil {
		if unmergedContents, err = loadDocument(unmergedDoc, locator); err != nil {
			return fmt.Errorf("load unmerged document: %w", err)
		}
	}
	changeLog, err := relocateNodes(inputContents, unmergedContents, patterns, selections, cmdConfig)
	if err != nil {
		return fmt.Errorf("relocate nodes: %w", err)
	}

	if !cmdConfig.Doc.Unmerge.DisableRewriting {
		logger.Debug("Document has been unmerged, rewriting the $refs")
		rewriteRefs(unmergedContents, locator, changeLog)
		rewriteRefs(inputContents, locator, changeLog)
	}

	logger.Info("Writing unmerged file", "file", unmergedPath)
	buf := bytes.NewBuffer(nil)
	enc, err := getDocumentEncoder(buf, cmdConfig)
	if err != nil {
		return fmt.Errorf("get encoder: %w", err)
	}

	if err = enc.Encode(unmergedContents); err != nil {
		return fmt.Errorf("marshal document: %w", err)
	}
	if err = os.WriteFile(unmergedPath, buf.Bytes(), 0o644); err != nil {
		return fmt.Errorf("write unmerged file %q: %w", unmergedPath, err)
	}

	modifiedPath := common2.Coalesce(cmdConfig.Doc.Unmerge.Output, cmd.Document)
	logger.Info("Writing modified document", "file", modifiedPath)
	buf = bytes.NewBuffer(nil)
	if enc, err = getDocumentEncoder(buf, cmdConfig); err != nil {
		return fmt.Errorf("get encoder: %w", err)
	}
	if err = enc.Encode(inputContents); err != nil {
		return fmt.Errorf("marshal document: %w", err)
	}
	if err = os.WriteFile(modifiedPath, buf.Bytes(), 0o644); err != nil {
		return fmt.Errorf("write modified contents to %q: %w", cmdConfig.Doc.Unmerge.Output, err)
	}

	return nil
}

type mergeableNode struct {
	node        *types.RawNode
	destination *types.RawNode
	directDeps  []*types.RawNode // Direct mergeable nodes that this mergeableNode depends on
	matched     bool
	relocated   bool
	orphaned    bool
}

func relocateNodes(sourceDoc, destDoc *documentTree, patterns []glob.Glob, selections []*types.RawNode, cmdConfig common2.ToolConfig) ([]changeLogEntry, error) {
	logger := log.GetLogger("")
	if sourceDoc == nil || destDoc == nil {
		panic("sourceDoc or destDoc is nil, this is a bug")
	}

	changeLog := relocateEssentialNodes(sourceDoc, destDoc)
	locator := common2.GetLocator(cmdConfig)
	mergeables, err := collectMergeableNodes(sourceDoc, destDoc, patterns, selections, locator)
	if err != nil {
		return nil, err
	}

	denoteNodes(mergeables)

	var relocatees []mergeableNode
	switch cmdConfig.Doc.Unmerge.IncludeDeps {
	case "none":
		relocatees = lo.Filter(mergeables, func(r mergeableNode, _ int) bool { return r.matched })
	case "orphaned-deps":
		relocatees = lo.Filter(mergeables, func(r mergeableNode, _ int) bool { return r.matched || r.orphaned })
	case "all":
		relocatees = lo.Filter(mergeables, func(r mergeableNode, _ int) bool { return r.relocated })
	default:
		return nil, fmt.Errorf("%w: unknown dependencies scope %q", common2.ErrWrongCliArgs, cmdConfig.Doc.Unmerge.IncludeDeps)
	}

	if len(relocatees) == 0 {
		return nil, fmt.Errorf("no objects selected to relocate, check your patterns or selections")
	}

	for _, r := range relocatees {
		var move bool
		switch cmdConfig.Doc.Unmerge.DuplicateObjects {
		case "none":
			move = true
		case "all-deps":
			move = r.matched
		case "shared-deps":
			move = r.matched || r.orphaned
		case "all":
			move = false
		default:
			return nil, fmt.Errorf("%w: unknown mode %q", common2.ErrWrongCliArgs, cmdConfig.Doc.Unmerge.DuplicateObjects)
		}

		var reason string
		switch {
		case r.matched && len(patterns) > 0:
			reason = "matched by pattern"
		case r.matched:
			reason = "selected interactively"
		case r.orphaned:
			reason = "an orphaned direct dependency"
		case r.relocated:
			reason = "a dependency"
		}
		logger.Info("Relocating object", "path", strings.Join(r.node.Path(), "."), "reason", reason, "action", lo.Ternary(move, "move", "duplicate"))
		change, err := copyNode(r.node, r.destination, destDoc.OriginDocument(), sourceDoc.OriginDocument(), cmdConfig)
		if err != nil {
			return nil, fmt.Errorf("copy node %v: %w", jsonpointer.PointerString(r.node.Path()...), err)
		}
		if change == nil {
			continue
		}

		if move && change.From != nil && change.To != nil {
			logger.Trace("-> Removing the original object", "source", change.From.String())
			if _, err = sourceDoc.DeleteByPath(change.From.Pointer); err != nil {
				return nil, fmt.Errorf("delete node by path %q: %w", change.From.String(), err)
			}
			change.Move = true
		}
		changeLog = append(changeLog, *change)
	}

	if err = cleanupMergeableMaps(sourceDoc, destDoc); err != nil {
		return nil, fmt.Errorf("cleanup mergeable maps: %w", err)
	}

	return changeLog, nil
}

func denoteNodes(mergeables []mergeableNode) {
	logger := log.GetLogger("")

	// Find mergeable dependencies of matched mergeables
	for changes := 1; changes > 0; {
		changes = 0
		for i := range len(mergeables) {
			if mergeables[i].relocated {
				continue
			}
			hasRelocatedDependents := lo.SomeBy(mergeables, func(r mergeableNode) bool {
				return r.relocated && lo.ContainsBy(r.directDeps, func(d *types.RawNode) bool {
					return d.AbsPointerString() == mergeables[i].node.AbsPointerString()
				})
			})
			if hasRelocatedDependents {
				logger.Trace("Marking object as relocated", "path", mergeables[i].node.Path())
				mergeables[i].relocated = true
				changes++
			}
		}
	}

	// Find orphaned mergeables -- the relocated mergeables that *only* matched or orphaned mergeables are depending on them.
	// In other words, they would become orphans after unmerging -- no any other mergeable would depend on them in the source document.
	for changes := 1; changes > 0; {
		changes = 0
		for i := range len(mergeables) {
			if !mergeables[i].relocated || mergeables[i].orphaned {
				continue
			}
			dependents := lo.Filter(mergeables, func(r mergeableNode, _ int) bool {
				return lo.ContainsBy(r.directDeps, func(d *types.RawNode) bool {
					return d.AbsPointerString() == mergeables[i].node.AbsPointerString()
				})
			})
			allDependentsAreMatched := len(dependents) > 0 && lo.EveryBy(dependents, func(r mergeableNode) bool { return r.matched })
			allDependenciesAreOrphanedOrNoDependencies := lo.EveryBy(mergeables[i].directDeps, func(d *types.RawNode) bool {
				r, _ := lo.Find(mergeables, func(r mergeableNode) bool { return r.node.AbsPointerString() == d.AbsPointerString() })
				return r.orphaned
			})
			if allDependentsAreMatched && allDependenciesAreOrphanedOrNoDependencies {
				logger.Trace("Marking object as orphaned", "path", mergeables[i].node.Path())
				mergeables[i].orphaned = true
				changes++
			}
		}
	}
}

func cleanupMergeableMaps(sourceDoc, destDoc *documentTree) error {
	logger := log.GetLogger("")

	// Clean up the empty mergeable maps in the both documents
	for _, d := range []*documentTree{sourceDoc, destDoc} {
		for _, m := range d.MergeableMaps() {
			if m != nil && m.IsZero() {
				logger.Trace("Removing empty mergeable map", "path", m.Path())
				if _, err := d.DeleteByPath(m.Path()); err != nil {
					return fmt.Errorf("delete node by path %q: %w", jsonpointer.PointerString(m.Path()...), err)
				}
			}
		}
	}
	return nil
}

func collectMergeableNodes(sourceDoc, destDoc *documentTree, patterns []glob.Glob, selections []*types.RawNode, locator common2.DocumentLocator) ([]mergeableNode, error) {
	var mergeables []mergeableNode
	logger := log.GetLogger("")

	for sMap, dMap := range utils.ZipLongest2(sourceDoc.MergeableMaps(), destDoc.MergeableMaps()) {
		switch {
		case sMap == nil:
			continue // Source is empty, nothing to merge
		case sMap.Kind() != types.RawNodeKindObject:
			return nil, fmt.Errorf("expected an object on path %q in document %q", path.Join(sMap.Path()...), sourceDoc.OriginDocument())
		case sMap.Len() == 0:
			logger.Trace("Source map is empty, skipping", "path", sMap.Path())
			continue
		}

		switch {
		case dMap == nil:
			dMap = types.NewEmptyRawNode(types.RawNodeKindObject, sMap.Path(), sMap.OriginDocument())
			if err := destDoc.SetNodeByPath(dMap); err != nil {
				return nil, fmt.Errorf("create object on path %q in document %q: %w", path.Join(sMap.Path()...), destDoc.OriginDocument(), err)
			}
		case dMap.Kind() != types.RawNodeKindObject:
			return nil, fmt.Errorf("expected an object on path %q in document %q", path.Join(dMap.Path()...), destDoc.OriginDocument())
		}

		logger.Trace("Enumerating source map entries", "path", sMap.Path(), "entriesCount", sMap.Len())
		for sKey, sNode := range sMap.Entries() {
			var matched bool
			if len(patterns) > 0 {
				nodePath := strings.Join(sNode.Path(), ".")
				matched = lo.SomeBy(patterns, func(p glob.Glob) bool { return p.Match(nodePath) })
			} else {
				matched = lo.ContainsBy(selections, func(n *types.RawNode) bool { return n.AbsPointerString() == sNode.AbsPointerString() })
			}

			logger.Debug("Collecting mergeable dependencies for object", "path", sNode.Path(), "key", sKey, "matched", matched)
			deps := collectDirectMergeableDeps(sNode, []*documentTree{sourceDoc, destDoc}, locator)
			logger.Trace("Found object", "path", sNode.Path(), "key", sKey, "path", sNode.Path(), "matched", matched, "dependenciesCount", len(deps))
			mergeables = append(mergeables, mergeableNode{node: sNode, destination: dMap, directDeps: deps, matched: matched, relocated: matched})
		}
	}

	return mergeables, nil
}

// promptSelectMergeableObjects prints the numbered list of mergeable objects and reads the user's selection from in.
// The user types comma-separated values, each of which is a single number or a number range with optional bounds
// (e.g. "2-4", "-5", "3-"), then hits Enter to proceed. Pressing Ctrl-D on an empty line cancels: cancelled is true.
func promptSelectMergeableObjects(inputDoc, outputDoc *jsonpointer.JSONPointer, nodes []*types.RawNode, out io.Writer, in io.Reader) ([]int, error) {
	var indexes []int

	for {
		fmt.Fprintf(out, "Please select objects to relocate from %s to %s:\n", inputDoc, outputDoc)
		for i, n := range nodes {
			mark := lo.Ternary(lo.Contains(indexes, i), "*", " ")
			fmt.Fprintf(out, "%s %2d: %s\n", mark, i+1, strings.Join(n.Path(), "."))
		}
		fmt.Fprint(out, "Enter numbers or ranges (e.g. 1,3,5-7,-3,4-) or press Ctrl-D to exit: ")

		line, err := bufio.NewReader(in).ReadString('\n')
		switch {
		case errors.Is(err, io.EOF):
			fmt.Fprintln(out, "Aborted.")
			return nil, common2.ErrInterruptedByUser
		case err != nil:
			return nil, fmt.Errorf("read input: %w", err)
		case strings.TrimSpace(line) == "":
			if len(indexes) > 0 {
				return indexes, nil
			}
			fmt.Fprint(out, "Nothing selected, try again or press Ctrl-D to exit\n\n")
			continue
		}

		selections, err := parseSelectionRanges(line, len(nodes))
		if err != nil {
			fmt.Fprintf(out, "Invalid selection, try again: %s\n", err)
		}
		indexes = lo.Uniq(append(indexes, lo.Map(selections, func(i int, _ int) int { return i - 1 })...))
	}
}

// parseSelectionRanges parses a comma-separated list of numbers and ranges into a set of 1-based ordinals.
// A token is either a single number ("5"), a full range ("2-4"), or a range with an omitted bound: "-5" means
// 1..5 and "3-" means 3..max. All ordinals must lie within [1, max].
func parseSelectionRanges(input string, maximum int) ([]int, error) {
	var selections []int
	if input == "" {
		return nil, fmt.Errorf("empty input")
	}
	input = strings.TrimSpace(input)

	for _, token := range strings.Split(input, ",") {
		token = strings.TrimSpace(token)
		if token == "" {
			continue
		}

		var start, end int
		if strings.Contains(token, "-") {
			parts := strings.SplitN(token, "-", 2)
			vals := [2]int{1, maximum}
			for i, p := range parts {
				if s := strings.TrimSpace(p); s != "" {
					v, convErr := strconv.Atoi(s)
					if convErr != nil {
						return nil, fmt.Errorf("invalid selection %q", token)
					}
					vals[i] = v
				}
			}
			start, end = vals[0], vals[1]
		} else {
			v, convErr := strconv.Atoi(token)
			if convErr != nil {
				return nil, fmt.Errorf("invalid selection %q", token)
			}
			start, end = v, v
		}

		if start > end {
			return nil, fmt.Errorf("invalid range %q: start greater than end", token)
		}
		if start < 1 || end > maximum {
			return nil, fmt.Errorf("selection %q is out of range [1, %d]", token, maximum)
		}
		for i := start; i <= end; i++ {
			selections = append(selections, i)
		}
	}

	return selections, nil
}

func collectDirectMergeableDeps(node *types.RawNode, docs []*documentTree, locator common2.DocumentLocator) []*types.RawNode {
	logger := log.GetLogger("")
	if node == nil {
		return nil
	}
	if node.Kind() == types.RawNodeKindScalar {
		return nil
	}

	var res []*types.RawNode
	for _, r := range collectRefs(node) {
		ref, err := parseRefRawNode(r)
		if err != nil {
			logger.Warn("Failed to parse $ref, skipping", "path", r.Path(), "error", err)
			continue
		}

		// Explicit document path where this $ref pointed to. For internal $ref, it's the file itself
		referredPath := r.OriginDocument()
		if ref.Location() != "" {
			// Resolve location in external $ref relative to it's origin document location
			if referredPath, err = locator.ResolveURL(r.OriginDocument(), ref); err != nil {
				logger.Error("Failed to resolve $ref, skipping", "path", r.Path(), "value", ref, "error", err)
				continue
			}
		}

		logger.Trace("Found $ref", "path", r.Path(), "pointer", ref.String())
		referredDoc, found := lo.Find(docs, func(d *documentTree) bool { return absLocation(d.OriginDocument()) == absLocation(referredPath) })
		if !found {
			logger.Trace("-> $ref points to 3rd-party document, skipping", "path", r.Path(), "pointer", ref.String())
			// 3rd-party document
			continue
		}

		mKeys, mCompKeys := referredDoc.MergeableMapPaths()
		mPaths := append(
			lo.Map(mKeys, func(k string, _ int) []string { return []string{k} }),
			lo.Map(mCompKeys, func(k string, _ int) []string { return []string{"components", k} })...)

		// Load the mergeable node even if $ref points to its nested node.
		var refNode *types.RawNode
		for _, p := range mPaths {
			if rest, ok := lo.CutPrefix(ref.Pointer, p); ok && len(rest) > 0 {
				key := append(p, rest[0]) // nolint:gocritic
				if refNode = referredDoc.GetByPath(key); refNode == nil {
					logger.Warn("Invalid $ref, skipping", "path", r.Path(), "pointer", ref.PointerString())
				}
				break
			}
		}
		if refNode == nil {
			logger.Trace("-> $ref points to non-mergeable or invalid node, skipping", "path", r.Path(), "pointer", ref.String())
			continue
		}
		logger.Debug("Found mergeable dependency node", "path", r.Path(), "pointer", ref.String(), "document", referredDoc.OriginDocument())
		res = append(res, refNode)
	}

	// Eliminate possible duplicates
	res = lo.UniqBy(res, func(n *types.RawNode) string { return n.AbsPointerString() })
	return res
}
