package doc

import (
	"bufio"
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"hash/crc64"
	"io"
	"os"
	"path"
	"slices"
	"strconv"
	"strings"

	"github.com/bdragon300/go-asyncapi/cmd/go-asyncapi/common"
	"github.com/bdragon300/go-asyncapi/internal/compiler"
	"github.com/bdragon300/go-asyncapi/internal/jsonpointer"
	"github.com/bdragon300/go-asyncapi/internal/log"
	"github.com/bdragon300/go-asyncapi/internal/types"
	"github.com/bdragon300/go-asyncapi/internal/utils"
	"github.com/gobwas/glob"
	"github.com/samber/lo"
	"gopkg.in/yaml.v3"
)

type UnmergeCmd struct {
	Document string `arg:"positional,required" help:"AsyncAPI document file or URL" placeholder:"FILE"`
	// TODO: add docs url link
	Patterns         []string `arg:"positional" help:"Globbing pattern of the objects to move" placeholder:"PATTERN"`
	Scope            string   `arg:"--scope,-s" help:"Scope of objects to consider. Possible values: matched, auto, all" placeholder:"SCOPE"`
	Duplicate        string   `arg:"--duplicate,-d" help:"Objects to duplicate instead of moving. Possible values: none, offscope-deps, all" placeholder:"DUPLICATE"`
	Output           string   `arg:"--output,-o" help:"Output file path. By default, the file name is autogenerated" placeholder:"FILE"`
	DisableRewriting bool     `arg:"--disable-rewriting" help:"Do not rewrite $refs"`
}

func cliUnmerge(cmd *UnmergeCmd, cmdConfig common2.ToolConfig) error {
	logger := log.GetLogger("")

	outputBuf := bytes.NewBuffer(nil)
	var enc anyEncoder
	switch cmdConfig.Doc.Format {
	case "json":
		logger.Debug("Using JSON output format", "indent", cmdConfig.Doc.Indent)
		e := json.NewEncoder(outputBuf)
		e.SetIndent("", strings.Repeat(" ", cmdConfig.Doc.Indent))
		enc = e
	case "yaml":
		logger.Debug("Using YAML output format", "indent", cmdConfig.Doc.Indent)
		e := yaml.NewEncoder(outputBuf)
		e.SetIndent(cmdConfig.Doc.Indent)
		enc = e
	default:
		return fmt.Errorf("%w: unknown output format %q", common2.ErrWrongCliArgs, cmdConfig.Doc.Format)
	}

	outputPath := cmd.Output
	if outputPath == "" {
		// Append a checksum of document arguments to generate a unique output file name per combination of input documents
		b := lo.FlatMap(cmd.Patterns, func(doc string, _ int) []byte { return append([]byte(doc), 0) })
		sum := crc64.Checksum(b, crc64.MakeTable(crc64.ECMA))
		outputPath = fmt.Sprintf("unmerged_%s_%x.%s", strings.TrimSuffix(cmd.Document, path.Ext(cmd.Document)), sum, cmdConfig.Doc.Format)
	}
	outputDoc, err := jsonpointer.Parse(outputPath)
	if err != nil {
		return fmt.Errorf("parse output path as url: %w", err)
	}
	if outputDoc.URI != nil {
		return fmt.Errorf("writing to documents by URL is not supported, please provide a file path")
	}

	inputDoc, err := jsonpointer.Parse(cmd.Document)
	if err != nil {
		return fmt.Errorf("parse document url %q: %w", cmd.Document, err)
	}
	if inputDoc.URI != nil {
		return fmt.Errorf("modifying documents by URL is not supported, you can use --copy flag for read-only mode")
	}

	inputContents := newDocumentTree(inputDoc)
	logger.Debug("Loading document", "url", inputDoc)
	locator := common2.GetLocator(cmdConfig)
	buf, newDecoder, err := compiler.ReadDocument(inputDoc, locator, logger)
	if err != nil {
		return fmt.Errorf("read document: %w", err)
	}
	if err = newDecoder(bytes.NewReader(buf)).Decode(&inputContents); err != nil {
		return fmt.Errorf("decode document: %w", err)
	}

	patterns := lo.Map(cmd.Patterns, func(p string, _ int) glob.Glob {
		g, err := glob.Compile(p)
		if err != nil {
			panic(fmt.Sprintf("invalid glob pattern %q: %v", p, err)) // This should be caught by arg parsing validation
		}
		return g
	})
	var selections []*types.RawNode
	if len(patterns) == 0 {
		// Interactive mode
		logger.Debug("No patterns provided, switching to interactive mode")
		mergeableNodes := lo.FlatMap(inputContents.MergeableMaps(), func(m *types.RawNode, _ int) []*types.RawNode {
			if m == nil || m.Kind() != types.RawNodeKindObject {
				return nil
			}
			var res []*types.RawNode
			for _, e := range m.Entries() {
				res = append(res, e)
			}
			return res
		})
		selectedIndexes, cancelled := promptSelectMergeableObjects(mergeableNodes, os.Stdout, os.Stdin)
		if cancelled {
			logger.Debug("Cancelled, nothing to do")
			return nil
		}
		selections = lo.Map(selectedIndexes, func(i int, _ int) *types.RawNode { return mergeableNodes[i] })
	}

	outputContents := newDocumentTree(outputDoc)
	changeLog, err := unmergeDocument(inputContents, outputContents, patterns, selections, cmdConfig)
	if err != nil {
		return fmt.Errorf("unmerge documents: %w", err)
	}

	if !cmdConfig.Doc.Unmerge.DisableRewriting {
		logger.Debug("Document unmerged, rewriting the $refs")
		rewriteRefs(outputContents, locator, changeLog)
	}

	logger.Info("Writing output file", "file", outputPath)
	if err = enc.Encode(outputContents); err != nil {
		return fmt.Errorf("marshal output document to yaml: %w", err)
	}
	if err = os.WriteFile(outputPath, outputBuf.Bytes(), 0o644); err != nil {
		return fmt.Errorf("write output file %q: %w", outputPath, err)
	}

	return nil
}

type mergeableNode struct {
	node        *types.RawNode
	destination *types.RawNode
	deps        []*types.RawNode // Nodes that this mergeable depends on
	matched     bool
	relocated   bool
	isolated    bool
}

func unmergeDocument(sourceDoc, destDoc *documentTree, patterns []glob.Glob, selections []*types.RawNode, cmdConfig common2.ToolConfig) ([]changeLogEntry, error) {
	logger := log.GetLogger("")
	if sourceDoc == nil || destDoc == nil {
		panic("sourceDoc or destDoc is nil, this is a bug")
	}

	locator := common2.GetLocator(cmdConfig)
	mergeables, entries, err := collectMergeableNodes(sourceDoc, destDoc, patterns, selections, locator)
	if err != nil {
		return entries, err
	}

	// Find other mergeables that matched mergeables are depending on.
	for changes := 1; changes > 0; {
		changes = 0
		for i := range len(mergeables) {
			if mergeables[i].relocated {
				continue
			}
			relocatedMergeables := lo.Filter(mergeables, func(r mergeableNode, _ int) bool { return r.relocated })
			isDependency := lo.SomeBy(relocatedMergeables, func(r mergeableNode) bool {
				return slices.Contains(r.deps, mergeables[i].node)
			})
			if isDependency {
				logger.Trace("Marking object as relocated", "path", mergeables[i].node.Path())
				mergeables[i].relocated = true
				changes++
			}
		}
	}

	// Find isolated mergeables -- the relocated mergeables that only matched or isolated mergeables are depending on them.
	// In other words, mergeables that would become orphaned in the source document after doing the unmerge command.
	for changes := 1; changes > 0; {
		changes = 0
		for i := range len(mergeables) {
			if !mergeables[i].relocated || mergeables[i].isolated {
				continue
			}
			deps := lo.Filter(mergeables, func(r mergeableNode, _ int) bool {
				return slices.Contains(r.deps, mergeables[i].node)
			})
			isolated := lo.EveryBy(deps, func(r mergeableNode) bool { return r.matched || r.isolated })
			if isolated {
				logger.Trace("Marking object as isolated", "path", mergeables[i].node.Path())
				mergeables[i].isolated = true
				changes++
			}
		}
	}

	var relocateMergeables []mergeableNode
	switch cmdConfig.Doc.Unmerge.Scope {
	case "matched":
		relocateMergeables = lo.Filter(mergeables, func(r mergeableNode, _ int) bool { return r.matched })
	case "auto":
		relocateMergeables = lo.Filter(mergeables, func(r mergeableNode, _ int) bool { return r.matched || r.isolated })
	case "all":
		relocateMergeables = lo.Filter(mergeables, func(r mergeableNode, _ int) bool { return r.relocated })
	default:
		return nil, fmt.Errorf("%w: unknown dependencies scope %q", common2.ErrWrongCliArgs, cmdConfig.Doc.Unmerge.Scope)
	}

	var changeLog []changeLogEntry
	for _, r := range relocateMergeables {
		logger.Debug("Relocating object", "path", r.node.Path(), "matched", r.matched, "relocated", r.relocated, "isolated", r.isolated)
		change, err := copyNode(r.node, r.destination, destDoc.OriginDocument(), sourceDoc.OriginDocument(), cmdConfig)
		if err != nil {
			return nil, fmt.Errorf("copy node %v: %w", jsonpointer.PointerString(r.node.Path()...), err)
		}
		if change == nil {
			continue
		}

		var toDelete bool
		switch cmdConfig.Doc.Unmerge.Duplicate {
		case "none":
			toDelete = r.matched
		case "offscope-deps":
			toDelete = r.matched || r.isolated
		case "all":
			toDelete = false
		default:
			return nil, fmt.Errorf("%w: unknown unmerge mode %q", common2.ErrWrongCliArgs, cmdConfig.Doc.Unmerge.Duplicate)
		}
		if toDelete && change.Source != nil && change.Destination != nil {
			logger.Trace("-> Removing the original object", "source", change.Source.String())
			sourceDoc.DeleteByPath(change.Source.Pointer)
			change.Move = true
		}
		changeLog = append(changeLog, *change)
	}

	return changeLog, nil
}

func collectMergeableNodes(sourceDoc *documentTree, destDoc *documentTree, patterns []glob.Glob, selections []*types.RawNode, locator common2.DocumentLocator) ([]mergeableNode, []changeLogEntry, error) {
	var mergeables []mergeableNode
	logger := log.GetLogger("")

	for sMap, dMap := range utils.ZipLongest2(sourceDoc.MergeableMaps(), destDoc.MergeableMaps()) {
		switch {
		case sMap == nil:
			continue // Source is empty, nothing to merge
		case sMap.Kind() != types.RawNodeKindObject:
			return nil, nil, fmt.Errorf("expected an object on path %q in document %q", path.Join(sMap.Path()...), sourceDoc.OriginDocument())
		case sMap.Len() == 0:
			logger.Trace("Source map is empty, skipping", "path", sMap.Path())
			continue
		}

		switch {
		case dMap == nil:
			dMap = sMap.CloneZero()
			destDoc.SetByPath(dMap.Path(), dMap)
		case dMap.Kind() != types.RawNodeKindObject:
			return nil, nil, fmt.Errorf("expected an object on path %q in document %q", path.Join(dMap.Path()...), destDoc.OriginDocument())
		}

		logger.Trace("Enumerating source map entries", "path", sMap.Path(), "entriesCount", sMap.Len())
		for sKey, sNode := range sMap.Entries() {
			var matched bool
			if len(patterns) > 0 {
				nodePath := strings.Join(sNode.Path(), ".")
				matched = lo.SomeBy(patterns, func(p glob.Glob) bool { return p.Match(nodePath) })
			} else {
				matched = lo.ContainsBy(selections, func(n *types.RawNode) bool { return n.AbsPointerString() == sNode.AbsPointerString() })
			}

			logger.Debug("Collecting mergeable dependencies for object", "path", sNode.Path(), "key", sKey, "matched", matched)
			deps := collectMergeableDependencies(sNode, []*documentTree{sourceDoc, destDoc}, locator)
			logger.Trace("Found object", "path", sNode.Path(), "key", sKey, "path", sNode.Path(), "matched", matched, "dependenciesCount", len(deps))
			mergeables = append(mergeables, mergeableNode{node: sNode, destination: dMap, deps: deps, matched: matched, relocated: matched})
		}
	}

	return mergeables, nil, nil
}

// promptSelectMergeableObjects prints the numbered list of mergeable objects and reads the user's selection from in.
// The user types comma-separated values, each of which is a single number or a number range with optional bounds
// (e.g. "2-4", "-5", "3-"), then hits Enter to proceed. Pressing Ctrl-D on an empty line cancels: cancelled is true.
func promptSelectMergeableObjects(nodes []*types.RawNode, out io.Writer, in io.Reader) (indexes []int, cancelled bool) {
	for {
		fmt.Fprintln(out, "Select objects:")
		for i, n := range nodes {
			mark := lo.Ternary(lo.Contains(indexes, i), "*", " ")
			fmt.Fprintf(out, "%s %2d: %s\n", mark, i+1, strings.Join(n.Path(), "."))
		}
		fmt.Fprintln(out, "Enter numbers or ranges (e.g. 1,3,5-7,-3,4-) or press Ctrl-D to exit: ")

		line, err := bufio.NewReader(in).ReadString('\n')
		switch {
		case errors.Is(err, io.EOF):
			fmt.Fprintln(out, "Aborted.")
			return nil, true
		case err != nil:
			panic(fmt.Errorf("read user input: %w", err))
		case strings.TrimSpace(line) == "":
			fmt.Fprintln(out)
			return nil, true
		}

		selections, err := parseSelectionRanges(line, len(nodes))
		switch {
		case err != nil:
			fmt.Fprintf(out, "Invalid selection, try again: %s\n", err)
		case len(selections) == 0:
			if len(indexes) > 0 {
				return indexes, false
			}
			fmt.Fprintln(out, "Nothing selected, try again or press Ctrl-D to exit")
		}
		indexes = lo.Uniq(append(indexes, lo.Map(selections, func(i int, _ int) int { return i - 1 })...))
	}
}

// parseSelectionRanges parses a comma-separated list of numbers and ranges into a set of 1-based ordinals.
// A token is either a single number ("5"), a full range ("2-4"), or a range with an omitted bound: "-5" means
// 1..5 and "3-" means 3..max. All ordinals must lie within [1, max].
func parseSelectionRanges(input string, maximum int) ([]int, error) {
	var selections []int
	if input == "" {
		return nil, fmt.Errorf("empty input")
	}
	input = strings.TrimSpace(input)

	for _, token := range strings.Split(input, ",") {
		token = strings.TrimSpace(token)
		if token == "" {
			continue
		}

		var start, end int
		if strings.Contains(token, "-") {
			parts := strings.SplitN(token, "-", 2)
			var vals [2]int
			for i, p := range parts {
				if s := strings.TrimSpace(p); s != "" {
					v, convErr := strconv.Atoi(s)
					if convErr != nil {
						return nil, fmt.Errorf("invalid selection %q", token)
					}
					vals[i] = v
				}
			}
			start, end = vals[0], vals[1]
		} else {
			v, convErr := strconv.Atoi(token)
			if convErr != nil {
				return nil, fmt.Errorf("invalid selection %q", token)
			}
			start, end = v, v
		}

		if start > end {
			return nil, fmt.Errorf("invalid range %q (start greater than end)", token)
		}
		if start < 1 || end > maximum {
			return nil, fmt.Errorf("selection %q is out of range [1, %d]", token, maximum)
		}
		for i := start; i <= end; i++ {
			selections = append(selections, i)
		}
	}

	return selections, nil
}

func collectMergeableDependencies(node *types.RawNode, docs []*documentTree, locator common2.DocumentLocator) []*types.RawNode {
	logger := log.GetLogger("")
	if node == nil {
		return nil
	}
	if node.Kind() == types.RawNodeKindScalar {
		return nil
	}

	var res []*types.RawNode
	queue := collectRefs(node)
	for i := 0; i < len(queue); i++ {
		ref, err := parseRefRawNode(queue[i])
		if err != nil {
			logger.Warn("Failed to parse $ref, skipping", "path", queue[i].Path(), "error", err)
			continue
		}

		// Explicit document path where this $ref pointed to. For internal $ref, it's the file itself
		referredPath := queue[i].OriginDocument()
		if ref.Location() != "" {
			// Resolve location in external $ref relative to it's origin document location
			if referredPath, err = locator.ResolveURL(queue[i].OriginDocument(), ref); err != nil {
				logger.Error("Failed to resolve $ref, skipping", "path", queue[i].Path(), "value", ref, "error", err)
				continue
			}
		}

		logger.Trace("Found $ref", "path", queue[i].Path(), "pointer", ref.String())
		referredDoc, found := lo.Find(docs, func(d *documentTree) bool { return absLocation(d.OriginDocument()) == absLocation(referredPath) })
		if !found {
			logger.Trace("-> $ref points to 3rd-party document, skipping", "path", queue[i].Path(), "pointer", ref.String())
			// 3rd-party document
			continue
		}

		mKeys, mCompKeys := referredDoc.MergeableMapPaths()
		mPaths := append(
			lo.Map(mKeys, func(k string, _ int) []string { return []string{k} }),
			lo.Map(mCompKeys, func(k string, _ int) []string { return []string{"components", k} })...)

		// Load the mergeable node even if $ref points to its nested node.
		var refNode *types.RawNode
		for _, p := range mPaths {
			if lo.HasPrefix(ref.Pointer, p) {
				if refNode = referredDoc.GetByPath(p); refNode == nil {
					logger.Warn("Invalid $ref, skipping", "path", queue[i].Path(), "pointer", ref.PointerString())
				}
				break
			}
		}
		if refNode == nil {
			logger.Trace("-> $ref points to non-mergeable or invalid node, skipping", "path", queue[i].Path(), "pointer", ref.String())
			continue
		}
		logger.Debug("Found mergeable dependency entry", "path", queue[i].Path(), "pointer", ref.String(), "document", referredDoc.OriginDocument())
		res = append(res, refNode)

		queue = append(queue, collectRefs(refNode)...)
		queue = lo.UniqBy(queue, func(n *types.RawNode) string {
			return n.AbsPointerString()
		})
	}

	return res
}
