// Code generated by go-asyncapi tool. DO NOT EDIT.

package messages

import (
	"encoding/json"
	"github.com/bdragon300/go-asyncapi/run"
	"github.com/bdragon300/go-asyncapi/run/kafka"
	"site-authorization/asyncapi/schemas"
)

// AuthResponseMsgOut-- (Outbound Message)
type AuthResponseMsgOut struct {
	Payload schemas.AuthEvent
	Headers map[string]any
}

func (m *AuthResponseMsgOut) WithPayload(payload schemas.AuthEvent) *AuthResponseMsgOut {
	m.Payload = payload
	return m
}

func (m *AuthResponseMsgOut) WithHeaders(headers map[string]any) *AuthResponseMsgOut {
	m.Headers = headers
	return m
}
func (m AuthResponseMsgOut) SetCorrelationID(value int) {

	v0 := m.Payload
	v0.ID = value

	m.Payload = v0
}

type AuthResponseMsgSender interface {
	Payload() schemas.AuthEvent
	Headers() map[string]any
	CorrelationID() (value int, err error)
}
type AuthResponseMsgReceiver interface {
	WithPayload(payload schemas.AuthEvent) *AuthResponseMsgOut
	WithHeaders(headers map[string]any) *AuthResponseMsgOut
	SetCorrelationID(value int)
}

// AuthResponseMsgIn-- (Inbound Message)
type AuthResponseMsgIn struct {
	payload schemas.AuthEvent
	headers map[string]any
}

func (m *AuthResponseMsgIn) Payload() schemas.AuthEvent {
	return m.payload
}

func (m *AuthResponseMsgIn) Headers() map[string]any {
	return m.headers
}
func (m AuthResponseMsgIn) CorrelationID() (value int, err error) {

	v0 := m.payload
	v1 := v0.ID
	value = v1
	return
}

func (m *AuthResponseMsgOut) MarshalAuthChannelKafka(envelope kafka.EnvelopeWriter) error {
	return m.MarshalEnvelopeKafka(envelope)
}

func (m *AuthResponseMsgOut) MarshalEnvelopeKafka(envelope kafka.EnvelopeWriter) error {

	// Default encoder
	enc := json.NewEncoder(envelope)
	if err := enc.Encode(m.Payload); err != nil {
		return err
	}
	envelope.SetContentType("application/json")
	envelope.SetHeaders(run.Headers(m.Headers))
	return nil
}

func (m *AuthResponseMsgIn) UnmarshalAuthChannelKafka(envelope kafka.EnvelopeReader) error {
	return m.UnmarshalEnvelopeKafka(envelope)
}
func (m *AuthResponseMsgIn) UnmarshalAuthResponseOperationKafka(envelope kafka.EnvelopeReader) error {
	return m.UnmarshalEnvelopeKafka(envelope)
}

func (m *AuthResponseMsgIn) UnmarshalEnvelopeKafka(envelope kafka.EnvelopeReader) error {

	// Default decoder
	dec := json.NewDecoder(envelope)
	if err := dec.Decode(&m.payload); err != nil {
		return err
	}
	m.headers = map[string]any(envelope.Headers())
	return nil
}
