// Code generated by go-asyncapi tool. DO NOT EDIT.

package messages

import (
	"encoding/json"
	"github.com/bdragon300/go-asyncapi/run"
	"io"
	"site-authorization/asyncapi/proto/kafka"
	"site-authorization/asyncapi/schemas"
)

type AuthResponseMsgSender interface {
	SetPayload(payload schemas.AuthEvent) *AuthResponseMsgOut
	SetHeaders(headers map[string]any) *AuthResponseMsgOut
	SetCorrelationID(value int) *AuthResponseMsgOut
}

// AuthResponseMsgOut-- (Outbound Message)
type AuthResponseMsgOut struct {
	Payload schemas.AuthEvent
	Headers map[string]any
}

func (m *AuthResponseMsgOut) SetPayload(payload schemas.AuthEvent) *AuthResponseMsgOut {
	m.Payload = payload
	return m
}

func (m *AuthResponseMsgOut) SetHeaders(headers map[string]any) *AuthResponseMsgOut {
	m.Headers = headers
	return m
}
func (m *AuthResponseMsgOut) SetCorrelationID(value int) *AuthResponseMsgOut {
	v0 := m.Payload

	v0.ID = value
	m.Payload = v0
	return m
}

type AuthResponseMsgReceiver interface {
	Payload() schemas.AuthEvent
	Headers() map[string]any
	CorrelationID() (value int, err error)
}

// AuthResponseMsgIn-- (Inbound Message)
type AuthResponseMsgIn struct {
	payload schemas.AuthEvent
	headers map[string]any
}

func (m *AuthResponseMsgIn) Payload() schemas.AuthEvent {
	return m.payload
}

func (m *AuthResponseMsgIn) Headers() map[string]any {
	return m.headers
}
func (m AuthResponseMsgIn) CorrelationID() (value int, err error) {
	v0 := m.payload

	// id
	v1 := v0.ID
	value = v1
	return
}

func (m *AuthResponseMsgOut) MarshalAuthChannelKafka(envelope kafka.EnvelopeWriter) error {
	return m.MarshalEnvelopeKafka(envelope)
}

func (m *AuthResponseMsgOut) MarshalEnvelopeKafka(envelope kafka.EnvelopeWriter) error {
	if err := m.MarshalKafka(envelope); err != nil {
		return err
	}
	envelope.SetContentType("application/json")
	envelope.SetHeaders(run.Headers(m.Headers))
	return nil
}

func (m *AuthResponseMsgOut) MarshalKafka(w io.Writer) error {
	// MIME type: application/json

	// Default encoder
	enc := json.NewEncoder(w)
	if err := enc.Encode(m.Payload); err != nil {
		return err
	}
	return nil
}

func (m *AuthResponseMsgIn) UnmarshalAuthChannelKafka(envelope kafka.EnvelopeReader) error {
	return m.UnmarshalEnvelopeKafka(envelope)
}

func (m *AuthResponseMsgIn) UnmarshalEnvelopeKafka(envelope kafka.EnvelopeReader) error {
	if err := m.UnmarshalKafka(envelope); err != nil {
		return err
	}
	m.headers = map[string]any(envelope.Headers())
	return nil
}

func (m *AuthResponseMsgIn) UnmarshalKafka(r io.Reader) error {
	// MIME type: application/json

	// Default decoder
	dec := json.NewDecoder(r)
	if err := dec.Decode(&m.payload); err != nil {
		return err
	}
	return nil
}
