package main

import (
	"bufio"
	"bytes"
	"fmt"
	"io"
	"os"
	"path"
	"path/filepath"
	"strings"
	"time"

	"github.com/bdragon300/go-asyncapi/internal/compiler"
	"github.com/bdragon300/go-asyncapi/internal/jsonpointer"
	"github.com/bdragon300/go-asyncapi/internal/log"
	"github.com/bdragon300/go-asyncapi/internal/types"
	"github.com/bdragon300/go-asyncapi/internal/utils"
	"github.com/samber/lo"
	"golang.org/x/term"
	"gopkg.in/yaml.v3"
)

const (
	defaultStdoutWidth              = 80
	sideBySideColumnSeparator       = " | "
	sideBySideLineNumberPrefixWidth = 6
)

type DocCmd struct {
	Merge      *DocMergeCmd `arg:"subcommand:merge" help:"Merge multiple AsyncAPI documents into one."`
	YAMLIndent int          `arg:"--yaml-indent" help:"Output YAML document indentation width" placeholder:"SPACES"`
}

type DocMergeCmd struct {
	Documents                  []string                   `arg:"positional,required" help:"AsyncAPI document file or url" placeholder:"FILE"`
	Output                     string                     `arg:"--output,-o" help:"Output file path. By default, the file name is autogenerated" placeholder:"FILE"`
	NonInteractive             bool                       `arg:"--non-interactive,-n" help:"Disable interactive mode"`
	ConflictResolutionStrategy toolConfigDocMergeStrategy `arg:"--conflict-resolution-strategy,-s" help:"Strategy to resolve name conflicts in non-interactive mode" placeholder:"STRATEGY"`
}

type docAsyncAPI struct {
	types.RawNode
	DocumentURL jsonpointer.JSONPointer `yaml:"-" json:"-"`
}

// CollectRefs collects pointers to all object RawNodes in the document that have a "$ref" key.
func (d docAsyncAPI) CollectRefs() []*types.RawNode {
	rootKeys, componentsKeys := d.mergeableKeys()
	res := lo.FlatMap(rootKeys, func(key string, _ int) []*types.RawNode {
		node, _ := d.Get(key)
		return collectRefs(node)
	})

	if comp, ok := d.Get("components"); ok {
		res = append(res, lo.FlatMap(componentsKeys, func(key string, _ int) []*types.RawNode {
			node, _ := comp.Get(key)
			return collectRefs(node)
		})...)
	}

	return res
}

func (d docAsyncAPI) MergeableNodes() []*types.RawNode {
	rootKeys, componentsKeys := d.mergeableKeys()
	res := lo.Map(rootKeys, func(key string, _ int) *types.RawNode {
		node, _ := d.Get(key)
		return node
	})
	if comp, ok := d.Get("components"); ok {
		res = append(res, lo.Map(componentsKeys, func(key string, _ int) *types.RawNode {
			node, _ := comp.Get(key)
			return node
		})...)
	}

	return res
}

func (d docAsyncAPI) mergeableKeys() ([]string, []string) {
	rootKeys := []string{"servers", "channels", "operations"}
	componentsKeys := []string{
		"schemas",
		"servers", "channels", "operations", "messages",
		"securitySchemes", "serverVariables", "parameters", "correlationIds", "replies", "replyAddresses", "externalDocs", "tags",
		"operationTraits", "messageTraits",
		"serverBindings", "channelBindings", "operationBindings", "messageBindings",
	}
	return rootKeys, componentsKeys
}

type docChangeLogEntry struct {
	Source, Destination *jsonpointer.JSONPointer
}

func cliDoc(cmd *DocCmd, globalConfig toolConfig) error {
	cmdConfig, err := cliDocConfig(globalConfig, cmd)
	if err != nil {
		return fmt.Errorf("config: %w", err)
	}

	if cmd.Merge != nil {
		return cliDocMerge(cmd.Merge, cmdConfig)
	}
	return fmt.Errorf("unknown doc subcommand")
}

func cliDocMerge(cmd *DocMergeCmd, cmdConfig toolConfig) error {
	logger := log.GetLogger("")
	if len(cmd.Documents) < 2 {
		return fmt.Errorf("expected two or more documents to be provided")
	}

	outputPath := cmd.Output
	if outputPath == "" {
		outputPath = fmt.Sprintf("merged_%s.yaml", time.Now().Format(time.RFC3339)) // FIXME: think again
	}
	outputPtr, err := jsonpointer.Parse(outputPath)
	if err != nil {
		return fmt.Errorf("parse output path as url: %w", err)
	}

	locator := getLocator(cmdConfig)
	var docURLs []*jsonpointer.JSONPointer
	var resultDocument *docAsyncAPI
	var changeLog []docChangeLogEntry
	for _, doc := range cmd.Documents {
		docURL, err := jsonpointer.Parse(doc)
		if err != nil {
			return fmt.Errorf("parse document url %q: %w", doc, err)
		}
		docURLs = append(docURLs, docURL)

		var contents docAsyncAPI
		logger.Debug("Loading document", "url", docURL)
		buf, newDecoder, err := compiler.ReadDocument(docURL, locator, logger)
		if err != nil {
			return fmt.Errorf("read document: %w", err)
		}
		if err = newDecoder(bytes.NewReader(buf)).Decode(&contents); err != nil {
			return fmt.Errorf("decode document: %w", err)
		}
		contents.DocumentURL = *docURL
		for _, ref := range contents.CollectRefs() {
			ref.Meta = docURL // Remember the origin document in ref metadata for later use when fixing $ref nodes
		}

		var changes []docChangeLogEntry
		if resultDocument, changes, err = docMergeDocuments(&contents, resultDocument, cmdConfig); err != nil {
			return fmt.Errorf("merge document %q: %w", docURL, err)
		}
		resultDocument.DocumentURL = *outputPtr
		changeLog = append(changeLog, changes...)
	}

	docRewriteRefs(resultDocument, docURLs, locator, changeLog)

	logger.Info("Writing output file", "file", outputPath)
	buf := bytes.NewBuffer(nil)
	enc := yaml.NewEncoder(buf)
	enc.SetIndent(cmdConfig.Doc.YAMLIndent)
	if err = enc.Encode(resultDocument); err != nil {
		return fmt.Errorf("marshal output document to yaml: %w", err)
	}
	if err = os.WriteFile(outputPath, buf.Bytes(), 0o644); err != nil {
		return fmt.Errorf("write output file %q: %w", outputPath, err)
	}
	logger.Debug("Writing complete")

	return nil
}

func docMergeDocuments(sourceDoc, destDoc *docAsyncAPI, cmdConfig toolConfig) (*docAsyncAPI, []docChangeLogEntry, error) {
	logger := log.GetLogger("")
	if destDoc == nil {
		return sourceDoc, nil, nil
	}
	if sourceDoc == nil {
		return destDoc, nil, nil
	}

	var changeLog []docChangeLogEntry
	// TODO: handle other fields: Info, DefaultContentType, etc.

	for src, dst := range utils.ZipLongest2(sourceDoc.MergeableNodes(), destDoc.MergeableNodes()) {
		if src == nil || dst == nil {
			continue
		}
		logger.Trace("Merging nodes", "source", src.Path(), "destination", dst.Path())
		switch {
		case src.Kind() != types.RawNodeKindObject:
			return nil, nil, fmt.Errorf("expected an object on path %q in document %q", path.Join(src.Path()...), sourceDoc.DocumentURL)
		case dst.Kind() != types.RawNodeKindObject:
			return nil, nil, fmt.Errorf("expected an object on path %q in document %q", path.Join(dst.Path()...), destDoc.DocumentURL)
		case src.Len() == 0 && dst.Len() == 0:
			logger.Trace("Both nodes are empty, skipping", "source", src.Path(), "destination", dst.Path())
			continue
		}
		changes, err := docMergeMaps(dst, src, destDoc.DocumentURL.Join(src.Path()...), sourceDoc.DocumentURL.Join(dst.Path()...), cmdConfig)
		if err != nil {
			return nil, nil, fmt.Errorf("merge maps %v: %w", path.Join(dst.Path()...), err)
		}
		changeLog = append(changeLog, changes...)
	}

	return destDoc, changeLog, nil
}

func docMergeMaps(destMap, srcMap *types.RawNode, dest, src jsonpointer.JSONPointer, cmdConfig toolConfig) ([]docChangeLogEntry, error) {
	logger := log.GetLogger("")
	var changeLog []docChangeLogEntry

	for skey, sval := range srcMap.Entries() {
		logger.Trace("Merging key", "key", skey, "path", sval.Path())

		skeystr := skey.(string) // Keys in two maps to merge are expected to be strings
		dval, conflict := destMap.Get(skey)
		if !conflict {
			logger.Trace("Moving object to destination", "key", skeystr, "value", sval)
			destMap.Set(skey, sval)
			changeLog = append(changeLog, docChangeLogEntry{Source: lo.ToPtr(src.Join(skeystr)), Destination: lo.ToPtr(dest.Join(skeystr))})
			continue
		} else if dval.Equal(sval) {
			logger.Info("Destination is equal to source object, ignoring", "destination", dval.Path(), "source", sval.Path())
			changeLog = append(changeLog, docChangeLogEntry{Source: lo.ToPtr(src.Join(skeystr)), Destination: lo.ToPtr(dest.Join(skeystr))})
			continue
		}

		logger.Debug("Conflict", "destination", dest.Join(skeystr), "source", src.Join(skeystr))
		changeEntry, err := docResolveKeyConflict(dval, sval, dest.Join(skeystr), src.Join(skeystr), cmdConfig)
		if err != nil {
			return nil, fmt.Errorf("resolve key conflict for key %q: %w", skeystr, err)
		}
		changeLog = append(changeLog, changeEntry)

		// Apply a change
		if changeEntry.Destination == nil || len(changeEntry.Destination.Pointer) == 0 {
			logger.Debug("Ignoring source object", "destination", dest.Join(skeystr), "source", src.Join(skeystr))
			continue
		}
		dKey := changeEntry.Destination.Pointer[len(changeEntry.Destination.Pointer)-1]
		logger.Debug("Moving destination object", "destination", dest.Join(skeystr), "source", src.Join(skeystr), "name", dKey)
		destMap.Set(dKey, sval)
	}

	return changeLog, nil
}

func docResolveKeyConflict(dMap, sMap *types.RawNode, dPath, sPath jsonpointer.JSONPointer, cmdConfig toolConfig) (docChangeLogEntry, error) {
	logger := log.GetLogger("")

	logMsg := "Auto-resolve conflict"
	strategy := cmdConfig.Doc.Merge.ConflictResolutionStrategy
	if !cmdConfig.Doc.Merge.NonInteractive { // TODO: use quiet mode flag
		answers := map[string]toolConfigDocMergeStrategy{
			"i": ToolConfigDocMergeStrategyIgnore,
			"o": ToolConfigDocMergeStrategyOverwrite,
			"r": ToolConfigDocMergeStrategyRename,
			"":  ToolConfigDocMergeStrategyRename,
		}
		fmt.Printf("Conflict! Object %q exists both in %q and %q\n", sPath.PointerString(), sPath.Location(), dPath.Location())

		for {
			fmt.Print("Choose option: (s)how diff/(i)gnore/(o)verwrite/(r)ename: [s/i/o/R]: ")
			var choice string
			inp := bufio.NewScanner(os.Stdin)
			if !inp.Scan() {
				return docChangeLogEntry{}, fmt.Errorf("read user choice: %w", inp.Err())
			}
			choice = inp.Text()
			var ok bool
			if strategy, ok = answers[strings.ToLower(choice)]; ok {
				break
			}
			if strings.ToLower(choice) != "s" {
				logger.Error("Invalid input, try again")
				continue
			}

			// Print side-by-side diff in YAML format
			headers := []string{
				fmt.Sprintf("Source: %s", sPath.Location()),
				fmt.Sprintf("Destination: %s", dPath.Location()),
			}
			columns := []io.Reader{
				strings.NewReader(docFormatDiffContent(headers[0], sPath.Pointer, sMap, cmdConfig.Doc.YAMLIndent)),
				strings.NewReader(docFormatDiffContent(headers[1], dPath.Pointer, dMap, cmdConfig.Doc.YAMLIndent)),
			}

			termWidth := getTerminalWidth()
			logger.Trace("Terminal width", "width", termWidth)
			colOutput, err := utils.ArrangeInColumns(columns, termWidth-sideBySideLineNumberPrefixWidth, sideBySideColumnSeparator)
			if err != nil {
				return docChangeLogEntry{}, fmt.Errorf("format diff view: %w", err)
			}
			fmt.Print(utils.ReadAllWithLineNumbers(strings.NewReader(colOutput), 2, sideBySideLineNumberPrefixWidth))
		}

		logMsg = "Conflict resolved by user"
	}

	key := sPath.Pointer[len(sPath.Pointer)-1]
	switch strategy {
	case ToolConfigDocMergeStrategyIgnore:
		logger.Info(logMsg, "action", "ignore", "destination", dPath, "source", sPath)
		return docChangeLogEntry{Source: &sPath, Destination: nil}, nil
	case ToolConfigDocMergeStrategyOverwrite:
		logger.Info(logMsg, "action", "overwrite", "destination", dPath, "source", sPath)
		return docChangeLogEntry{Source: &sPath, Destination: &dPath}, nil
	case ToolConfigDocMergeStrategyRename:
		dPath.Pointer = dPath.Pointer[:len(dPath.Pointer)-1]
		for i := 1; ; i++ {
			newKey := fmt.Sprintf("%s_%d", key, i)
			if _, exists := dMap.Get(newKey); !exists {
				logger.Info(logMsg, "action", "rename", "destination", dPath, "source", sPath, "newKey", newKey)
				return docChangeLogEntry{Source: &sPath, Destination: lo.ToPtr(dPath.Join(newKey))}, nil
			}
		}
	}

	panic(fmt.Sprintf("unknown conflict resolution strategy: %q", strategy))
}

func docFormatDiffContent(header string, ptr []string, contents *types.RawNode, indentWidth int) string {
	var indentLvl int
	var b strings.Builder

	b.WriteString(header)
	b.WriteString("\n\n")
	for _, p := range ptr {
		b.WriteString(strings.Repeat(" ", indentWidth*indentLvl))
		b.WriteString(p)
		b.WriteString(":\n")
		indentLvl++
	}

	buf := bytes.NewBuffer(nil)
	enc := yaml.NewEncoder(buf)
	enc.SetIndent(indentWidth)
	if err := enc.Encode(contents); err != nil {
		panic(fmt.Errorf("marshal diff content to yaml: %w", err))
	}

	lines := strings.Split(buf.String(), "\n")
	for _, line := range lines {
		b.WriteString(strings.Repeat(" ", indentWidth*indentLvl))
		b.WriteString(line)
		b.WriteString("\n")
	}

	return b.String()
}

func getTerminalWidth() int {
	if term.IsTerminal(int(os.Stdout.Fd())) {
		width, _, err := term.GetSize(int(os.Stdout.Fd()))
		if err != nil {
			panic(fmt.Errorf("get terminal size: %w", err))
		}
		return width
	}
	return defaultStdoutWidth
}

func docRewriteRefs(doc *docAsyncAPI, sourceDocs []*jsonpointer.JSONPointer, locator documentLocator, changeLog []docChangeLogEntry) {
	logger := log.GetLogger("")
	getAbsLoc := func(p *jsonpointer.JSONPointer) string {
		if p.FSPath != "" {
			return lo.Must(filepath.Abs(p.FSPath))
		}
		return p.Location()
	}

	for _, obj := range doc.CollectRefs() {
		if obj.Meta == nil {
			logger.Warn("Found $ref RawNode with empty metadata after merge, this is a bug", "path", obj.Path())
			continue
		}
		originPath := obj.Meta.(*jsonpointer.JSONPointer) // Document path where this $ref was before the merge
		targetPath := originPath                          // Explicit document path where this $ref pointed to before the merge

		// Extract jsonpointer from value of variant type
		var rawRef string
		variant, _ := obj.Get("$ref")
		if valid := variant.Kind() == types.RawNodeKindScalar; valid {
			if rawRef, valid = variant.AsScalar().(string); !valid {
				logger.Error("$ref value is expected to be string, skipping", "path", obj.Path(), "kind", variant.Kind())
				continue
			}
		}
		ref, err := jsonpointer.Parse(rawRef)
		if err != nil {
			logger.Error("Failed to parse $ref, skipping", "path", obj.Path(), "value", rawRef, "error", err)
			continue
		}
		newRef := *ref

		if ref.Location() != "" {
			// Resolve relative path in $ref against the origin path
			if targetPath, err = locator.ResolveURL(originPath, ref); err != nil {
				logger.Error("Failed to rewrite $ref, skipping", "path", obj.Path(), "value", rawRef, "error", err)
				continue
			}
			_, found := lo.Find(sourceDocs, func(docURL *jsonpointer.JSONPointer) bool {
				return getAbsLoc(docURL) == getAbsLoc(targetPath)
			})
			if found {
				// Make $ref internal (i.e. remove location) if it points to any of merged documents
				newRef.URI = nil
				newRef.FSPath = ""
			} else if newRef.FSPath != "" && doc.DocumentURL.FSPath != "" {
				// Rewrite $ref to 3rd-party file according to new location of merged document
				if p, err := filepath.Rel(path.Dir(getAbsLoc(&doc.DocumentURL)), getAbsLoc(targetPath)); err != nil {
					logger.Error("Failed to rewrite external location in $ref, leave it as-is", "path", obj.Path(), "value", rawRef, "error", err)
				} else {
					newRef.FSPath = p
				}
			}
		}

		// Rewrite pointer path in $ref if it points to an object (or its nested part) that was renamed during merge
		for _, change := range changeLog {
			rest, match := lo.CutPrefix(ref.Pointer, change.Source.Pointer)
			if match && getAbsLoc(targetPath) == getAbsLoc(change.Source) && change.Destination != nil {
				newRef.Pointer = append(change.Destination.Pointer, rest...) // nolint:gocritic
				break
			}
		}

		obj.Set("$ref", types.NewScalarRawNode(variant.Path(), newRef.String()))
	}
}

// collectRefs returns a list of pointer to all RawNodes (n itself and all nested objects) that have a "$ref" key.
func collectRefs(n *types.RawNode) []*types.RawNode {
	if n == nil {
		return nil
	}
	if n.Kind() == types.RawNodeKindScalar {
		return nil
	}

	var res []*types.RawNode
	for _, v := range n.Entries() {
		res = append(res, collectRefs(v)...)
	}
	if n.Kind() == types.RawNodeKindObject && n.Has("$ref") {
		res = append(res, n)
	}

	return res
}

func cliDocConfig(globalConfig toolConfig, cmd *DocCmd) (toolConfig, error) {
	res := globalConfig

	res.Doc.YAMLIndent = coalesce(cmd.YAMLIndent, globalConfig.Doc.YAMLIndent)
	res.Doc.Merge.NonInteractive = coalesce(cmd.Merge.NonInteractive, globalConfig.Doc.Merge.NonInteractive)
	res.Doc.Merge.ConflictResolutionStrategy = coalesce(cmd.Merge.ConflictResolutionStrategy, globalConfig.Doc.Merge.ConflictResolutionStrategy)

	return res, nil
}
