package main

import (
	"bufio"
	"bytes"
	"errors"
	"fmt"
	"io"
	"os"
	"path"
	"reflect"
	"strings"

	"github.com/bdragon300/go-asyncapi/internal/compiler"
	"github.com/bdragon300/go-asyncapi/internal/jsonpointer"
	"github.com/bdragon300/go-asyncapi/internal/log"
	"github.com/bdragon300/go-asyncapi/internal/types"
	"github.com/bdragon300/go-asyncapi/internal/utils"
	"github.com/samber/lo"
	"golang.org/x/term"
	"gopkg.in/yaml.v3"
)

const (
	defaultStdoutWidth              = 80
	sideBySideColumnSeparator       = " | "
	sideBySideLineNumberPrefixWidth = 6
)

// mergePaths is paths to fields to merge.
// First item is jsonpointer, second item is field path in docAsyncAPI which is used for reflection
var mergePaths = []lo.Tuple2[[]string, []string]{
	{A: []string{"servers"}, B: []string{"Servers"}},
	{A: []string{"channels"}, B: []string{"Channels"}},
	{A: []string{"operations"}, B: []string{"Operations"}},

	{A: []string{"components", "schemas"}, B: []string{"Components", "Schemas"}},

	{A: []string{"components", "servers"}, B: []string{"Components", "Servers"}},
	{A: []string{"components", "channels"}, B: []string{"Components", "Channels"}},
	{A: []string{"components", "operations"}, B: []string{"Components", "Operations"}},
	{A: []string{"components", "messages"}, B: []string{"Components", "Messages"}},

	{A: []string{"components", "securitySchemes"}, B: []string{"Components", "SecuritySchemes"}},
	{A: []string{"components", "serverVariables"}, B: []string{"Components", "ServerVariables"}},
	{A: []string{"components", "parameters"}, B: []string{"Components", "Parameters"}},
	{A: []string{"components", "correlationIds"}, B: []string{"Components", "CorrelationIDs"}},
	{A: []string{"components", "replies"}, B: []string{"Components", "Replies"}},
	{A: []string{"components", "replyAddresses"}, B: []string{"Components", "ReplyAddresses"}},
	{A: []string{"components", "externalDocs"}, B: []string{"Components", "ExternalDocs"}},
	{A: []string{"components", "tags"}, B: []string{"Components", "Tags"}},

	{A: []string{"components", "operationTraits"}, B: []string{"Components", "OperationTraits"}},
	{A: []string{"components", "messageTraits"}, B: []string{"Components", "MessageTraits"}},

	{A: []string{"components", "serverBindings"}, B: []string{"Components", "ServerBindings"}},
	{A: []string{"components", "channelBindings"}, B: []string{"Components", "ChannelBindings"}},
	{A: []string{"components", "operationBindings"}, B: []string{"Components", "OperationBindings"}},
	{A: []string{"components", "messageBindings"}, B: []string{"Components", "MessageBindings"}},
}

type DocCmd struct {
	Merge      *DocMergeCmd `arg:"subcommand:merge" help:"Merge multiple AsyncAPI documents into one."`
	YAMLIndent int          `arg:"--yaml-indent" help:"Output YAML document indentation width" placeholder:"SPACES"`
}

type DocMergeCmd struct {
	Documents                  []string                   `arg:"positional,required" help:"AsyncAPI document file or url" placeholder:"FILE"`
	Output                     string                     `arg:"--output,-o" help:"Output file path. By default, the file name is autogenerated" placeholder:"FILE"`
	NonInteractive             bool                       `arg:"--non-interactive,-n" help:"Disable interactive mode"`
	ConflictResolutionStrategy toolConfigDocMergeStrategy `arg:"--conflict-resolution-strategy,-s" help:"Strategy to resolve name conflicts in non-interactive mode" placeholder:"STRATEGY"`
}

type docAsyncAPI struct {
	Asyncapi           string                                          `json:"asyncapi,omitzero" yaml:"asyncapi,omitempty"`
	ID                 string                                          `json:"id,omitzero" yaml:"id,omitempty"`
	Info               types.OrderedMapTree                            `json:"info,omitzero" yaml:"info,omitempty"`
	Servers            *types.OrderedMap[string, types.OrderedMapTree] `json:"servers,omitzero" yaml:"servers,omitempty"`
	DefaultContentType string                                          `json:"defaultContentType,omitzero" yaml:"defaultContentType,omitempty"`
	Channels           *types.OrderedMap[string, types.OrderedMapTree] `json:"channels,omitzero" yaml:"channels,omitempty"`
	Operations         *types.OrderedMap[string, types.OrderedMapTree] `json:"operations,omitzero" yaml:"operations,omitempty"`
	Components         *docAsyncAPIComponents                          `json:"components,omitzero" yaml:"components,omitempty"`

	DocumentURL jsonpointer.JSONPointer `json:"-" yaml:"-"`
}

type docAsyncAPIComponents struct {
	Schemas *types.OrderedMap[string, types.OrderedMapTree] `json:"schemas,omitzero" yaml:"schemas,omitempty"`

	Servers    *types.OrderedMap[string, types.OrderedMapTree] `json:"servers,omitzero" yaml:"servers,omitempty"`
	Channels   *types.OrderedMap[string, types.OrderedMapTree] `json:"channels,omitzero" yaml:"channels,omitempty"`
	Operations *types.OrderedMap[string, types.OrderedMapTree] `json:"operations,omitzero" yaml:"operations,omitempty"`
	Messages   *types.OrderedMap[string, types.OrderedMapTree] `json:"messages,omitzero" yaml:"messages,omitempty"`

	SecuritySchemes *types.OrderedMap[string, types.OrderedMapTree] `json:"securitySchemes,omitzero" yaml:"securitySchemes,omitempty"`
	ServerVariables *types.OrderedMap[string, types.OrderedMapTree] `json:"serverVariables,omitzero" yaml:"serverVariables,omitempty"`
	Parameters      *types.OrderedMap[string, types.OrderedMapTree] `json:"parameters,omitzero" yaml:"parameters,omitempty"`
	CorrelationIDs  *types.OrderedMap[string, types.OrderedMapTree] `json:"correlationIds,omitzero" yaml:"correlationIds,omitempty"`
	Replies         *types.OrderedMap[string, types.OrderedMapTree] `json:"replies,omitzero" yaml:"replies,omitempty"`
	ReplyAddresses  *types.OrderedMap[string, types.OrderedMapTree] `json:"replyAddresses,omitzero" yaml:"replyAddresses,omitempty"`
	ExternalDocs    *types.OrderedMap[string, types.OrderedMapTree] `json:"externalDocs,omitzero" yaml:"externalDocs,omitempty"`
	Tags            *types.OrderedMap[string, types.OrderedMapTree] `json:"tags,omitzero" yaml:"tags,omitempty"`

	OperationTraits *types.OrderedMap[string, types.OrderedMapTree] `json:"operationTraits,omitzero" yaml:"operationTraits,omitempty"`
	MessageTraits   *types.OrderedMap[string, types.OrderedMapTree] `json:"messageTraits,omitzero" yaml:"messageTraits,omitempty"`

	ServerBindings    *types.OrderedMap[string, types.OrderedMapTree] `json:"serverBindings,omitzero" yaml:"serverBindings,omitempty"`
	ChannelBindings   *types.OrderedMap[string, types.OrderedMapTree] `json:"channelBindings,omitzero" yaml:"channelBindings,omitempty"`
	OperationBindings *types.OrderedMap[string, types.OrderedMapTree] `json:"operationBindings,omitzero" yaml:"operationBindings,omitempty"`
	MessageBindings   *types.OrderedMap[string, types.OrderedMapTree] `json:"messageBindings,omitzero" yaml:"messageBindings,omitempty"`
}

func cliDoc(cmd *DocCmd, globalConfig toolConfig) error {
	cmdConfig, err := cliDocConfig(globalConfig, cmd)
	if err != nil {
		return fmt.Errorf("config: %w", err)
	}

	if cmd.Merge != nil {
		return cliDocMerge(cmd.Merge, cmdConfig)
	}
	return fmt.Errorf("unknown doc subcommand")
}

func cliDocMerge(cmd *DocMergeCmd, cmdConfig toolConfig) error {
	logger := log.GetLogger("")

	if len(cmd.Documents) < 2 {
		return fmt.Errorf("expected two or more documents to be provided")
	}

	locator := getLocator(cmdConfig)
	var resultDocument *docAsyncAPI
	var err error
	docURLs := lo.Map(cmd.Documents, func(doc string, _ int) jsonpointer.JSONPointer {
		docURL, e := jsonpointer.Parse(doc)
		if e != nil {
			err = errors.Join(err, fmt.Errorf("parse path or url: %w", e))
		}
		return lo.FromPtr(docURL)
	})
	if err != nil {
		return err
	}

	outputPath := cmd.Output
	if outputPath == "" {
		fileNames := lo.Map(docURLs, func(docURL jsonpointer.JSONPointer, _ int) string {
			loc := docURL.Location()
			ext := path.Ext(loc)
			res, _ := strings.CutSuffix(path.Base(loc), ext)
			return res
		})
		outputPath = "merged_" + strings.Join(fileNames, "_") + ".yaml"
	}
	outputPtr, err := jsonpointer.Parse(outputPath)
	if err != nil {
		return fmt.Errorf("parse output path as url: %w", err)
	}

	for _, docURL := range docURLs {
		var document docAsyncAPI
		buf, newDecoder, err := compiler.ReadDocument(&docURL, locator, logger)
		if err != nil {
			return fmt.Errorf("read document: %w", err)
		}
		if err = newDecoder(bytes.NewReader(buf)).Decode(&document); err != nil {
			return fmt.Errorf("decode document: %w", err)
		}

		document.DocumentURL = docURL
		logger.Debug("Loaded document", "url", docURL)
		if resultDocument, err = docMergeDocuments(&document, resultDocument, cmdConfig); err != nil {
			return fmt.Errorf("merge document %q: %w", docURL, err)
		}
		resultDocument.DocumentURL = *outputPtr
	}

	logger.Info("Writing output file", "file", outputPath)
	buf := bytes.NewBuffer(nil)
	enc := yaml.NewEncoder(buf)
	enc.SetIndent(cmdConfig.Doc.YAMLIndent)
	if err = enc.Encode(resultDocument); err != nil {
		return fmt.Errorf("marshal output document to yaml: %w", err)
	}
	if err = os.WriteFile(outputPath, buf.Bytes(), 0o644); err != nil {
		return fmt.Errorf("write output file %q: %w", outputPath, err)
	}
	logger.Debug("Writing complete")

	return nil
}

func docMergeDocuments(source, dest *docAsyncAPI, cmdConfig toolConfig) (*docAsyncAPI, error) {
	if dest == nil {
		return source, nil
	}
	if source == nil {
		return dest, nil
	}
	res := *source

	// TODO: handle other fields: Info, DefaultContentType, etc.

	rvals := [2]reflect.Value{
		reflect.ValueOf(res),
		reflect.ValueOf(dest),
	}
	for _, mergePath := range mergePaths {
		ptr := mergePath.A
		var fields [2]reflect.Value
		var vals [2]types.OrderedMap[string, types.OrderedMapTree]
		for i, rval := range rvals {
			for _, f := range mergePath.B {
				rval = reflect.Indirect(rval).FieldByName(f)
				if rval.IsZero() {
					rval.Set(reflect.New(rval.Type().Elem()))
				}
			}
			fields[i] = rval
			vals[i] = lo.FromPtr(rval.Interface().(*types.OrderedMap[string, types.OrderedMapTree]))
		}
		if lo.EveryBy(vals[:], func(val types.OrderedMap[string, types.OrderedMapTree]) bool { return val.Len() == 0 }) {
			continue
		}
		newValue, err := docMergeMaps(source.DocumentURL.Join(ptr...), vals[0], dest.DocumentURL.Join(ptr...), vals[1], cmdConfig)
		if err != nil {
			return nil, fmt.Errorf("merge maps %v: %w", ptr, err)
		}
		fields[0].Elem().Set(reflect.ValueOf(newValue))
	}

	return &res, nil
}

func docMergeMaps(
	source jsonpointer.JSONPointer,
	sourceMap types.OrderedMap[string, types.OrderedMapTree],
	dest jsonpointer.JSONPointer,
	destMap types.OrderedMap[string, types.OrderedMapTree],
	cmdConfig toolConfig,
) (types.OrderedMap[string, types.OrderedMapTree], error) {
	logger := log.GetLogger("")
	var err error

	for sk, sv := range sourceMap.Entries() {
		dv, conflict := destMap.Get(sk)
		if !conflict {
			logger.Trace("Add left key", "key", dest.Join(sk), "value", sv)
			destMap.Set(sk, sv)
			continue
		} else if reflect.DeepEqual(dv, sv) {
			logger.Info("Drop completely equal right entity", "destination", dest.Join(sk), "source", source.Join(sk))
			continue
		}

		logger.Info("Entity name conflict", "destination", dest.Join(sk), "source", source.Join(sk))
		strategy := cmdConfig.Doc.Merge.ConflictResolutionStrategy
		if !cmdConfig.Doc.Merge.NonInteractive { // TODO: use quiet mode flag
			// Print entities in YAML format side-by-side and ask user to choose
			headers := []string{
				fmt.Sprintf("Source: %s", source.Location()),
				fmt.Sprintf("Destination: %s", dest.Location()),
			}
			columns := []io.Reader{
				strings.NewReader(docPrepareDiffContent(headers[0], source.Join(sk).Pointer, sv, cmdConfig.Doc.YAMLIndent)),
				strings.NewReader(docPrepareDiffContent(headers[1], dest.Join(sk).Pointer, dv, cmdConfig.Doc.YAMLIndent)),
			}

			termWidth := getTerminalWidth()
			logger.Trace("Terminal width", "width", termWidth)
			colOutput, err := utils.ArrangeInColumns(columns, termWidth-sideBySideLineNumberPrefixWidth, sideBySideColumnSeparator)
			if err != nil {
				return destMap, fmt.Errorf("print diff view: %w", err)
			}
			fmt.Print(utils.ReadAllWithLineNumbers(strings.NewReader(colOutput), 2, sideBySideLineNumberPrefixWidth))

			answers := map[string]toolConfigDocMergeStrategy{
				"k": ToolConfigDocMergeStrategyKeep,
				"o": ToolConfigDocMergeStrategyOverwrite,
				"r": ToolConfigDocMergeStrategyRename,
				"":  ToolConfigDocMergeStrategyRename,
			}
			for {
				fmt.Print("Naming conflict, choose option (k)eep/(o)verwrite/(r)ename: [k/o/R]: ")
				var choice string
				inp := bufio.NewScanner(os.Stdin)
				if !inp.Scan() {
					return destMap, fmt.Errorf("read user choice: %w", inp.Err())
				}
				choice = inp.Text()
				var ok bool
				if strategy, ok = answers[strings.ToLower(choice)]; ok {
					break
				}
				logger.Error("Invalid choice, try again")
			}
		}

		if destMap, err = docMergeMapKeys(destMap, sv, dest.Join(sk), source.Join(sk), strategy); err != nil {
			return destMap, err
		}
	}

	return destMap, nil
}

func docMergeMapKeys(lMap types.OrderedMap[string, types.OrderedMapTree], rVal types.OrderedMapTree, lPath, rPath jsonpointer.JSONPointer, strategy toolConfigDocMergeStrategy) (types.OrderedMap[string, types.OrderedMapTree], error) {
	logger := log.GetLogger("")

	key := rPath.Pointer[len(rPath.Pointer)-1]
	switch strategy {
	case ToolConfigDocMergeStrategyKeep:
		logger.Info("Resolve conflict", "action", "keep", "left", lPath, "right", rPath)
	case ToolConfigDocMergeStrategyOverwrite:
		logger.Info("Resolve conflict", "action", "overwrite", "left", lPath, "right", rPath)
		lMap.Set(key, rVal)
	case ToolConfigDocMergeStrategyRename:
		for i := 1; ; i++ {
			newKey := fmt.Sprintf("%s_%d", key, i)
			if _, exists := lMap.Get(newKey); !exists {
				lMap.Set(newKey, rVal)
				logger.Info("Resolve conflict", "action", "rename", "left", lPath, "newKey", newKey)
				return lMap, nil
			}
		}
	default:
		return lMap, fmt.Errorf("unknown conflict resolution strategy: %q", strategy)
	}
	return lMap, nil
}

func docPrepareDiffContent(header string, ptr []string, contents types.OrderedMapTree, indentWidth int) string {
	var indentLvl int
	var b strings.Builder

	b.WriteString(header)
	b.WriteString("\n\n")
	for _, p := range ptr {
		b.WriteString(strings.Repeat(" ", indentWidth*indentLvl))
		b.WriteString(p)
		b.WriteString(":\n")
		indentLvl++
	}

	buf := bytes.NewBuffer(nil)
	enc := yaml.NewEncoder(buf)
	enc.SetIndent(indentWidth)
	if err := enc.Encode(contents); err != nil {
		panic(fmt.Errorf("marshal diff content to yaml: %w", err))
	}

	lines := strings.Split(buf.String(), "\n")
	for _, line := range lines {
		b.WriteString(strings.Repeat(" ", indentWidth*indentLvl))
		b.WriteString(line)
		b.WriteString("\n")
	}

	return b.String()
}

func getTerminalWidth() int {
	if term.IsTerminal(int(os.Stdout.Fd())) {
		width, _, err := term.GetSize(int(os.Stdout.Fd()))
		if err != nil {
			panic(fmt.Errorf("get terminal size: %w", err))
		}
		return width
	}
	return defaultStdoutWidth
}

func cliDocConfig(globalConfig toolConfig, cmd *DocCmd) (toolConfig, error) {
	res := globalConfig

	res.Doc.YAMLIndent = coalesce(cmd.YAMLIndent, globalConfig.Doc.YAMLIndent)
	res.Doc.Merge.NonInteractive = coalesce(cmd.Merge.NonInteractive, globalConfig.Doc.Merge.NonInteractive)
	res.Doc.Merge.ConflictResolutionStrategy = coalesce(cmd.Merge.ConflictResolutionStrategy, globalConfig.Doc.Merge.ConflictResolutionStrategy)

	return res, nil
}
