// Code generated by go-asyncapi tool. DO NOT EDIT.

package operations

import (
	"context"
	"github.com/bdragon300/go-asyncapi/run"
	"site-authorization/asyncapi/channels"
	"site-authorization/asyncapi/messages"
	"site-authorization/asyncapi/proto/kafka"
)

type AuthRequestOperationServerKafka interface {
	OpenAuthChannelKafka(context.Context, channels.AuthChannelParameters, run.AnySecurityScheme) (*channels.AuthChannelKafka, error)
	OpenAuthRequestOperationKafka(context.Context, channels.AuthChannelParameters) (*AuthRequestOperationKafka, error)
	Producer() kafka.Producer
	Consumer() kafka.Consumer
}

func OpenAuthRequestOperationKafka(
	ctx context.Context,
	server AuthRequestOperationServerKafka,
	params channels.AuthChannelParameters,

) (*AuthRequestOperationKafka, error) {
	ch, err := channels.OpenAuthChannelKafka(
		ctx,
		server,
		params,
		nil,
		nil,
	)
	if err != nil {
		return nil, err
	}

	return &AuthRequestOperationKafka{
		Channel: ch,
	}, nil
}

type AuthRequestOperationChannelKafka interface {
	Close() error

	SealAuthRequestMsg(kafka.EnvelopeWriter, channels.AuthChannelEnvelopeMarshalerKafka) error
	PublishAuthRequestMsg(context.Context, channels.AuthChannelEnvelopeMarshalerKafka) error

	UnsealAuthRequestMsg(kafka.EnvelopeReader, channels.AuthChannelEnvelopeUnmarshalerKafka) error
	SubscribeAuthRequestMsg(context.Context, func(messages.AuthRequestMsgReceiver)) error
}

type AuthRequestOperationKafka struct {
	Channel AuthRequestOperationChannelKafka
}

func (c AuthRequestOperationKafka) Close() error {
	return c.Channel.Close()
}

func (o AuthRequestOperationKafka) SealAuthRequestMsg(
	envelope kafka.EnvelopeWriter,
	message channels.AuthChannelEnvelopeMarshalerKafka,
) error {
	return o.Channel.SealAuthRequestMsg(envelope, message)
}

func (o AuthRequestOperationKafka) PublishAuthRequestMsg(
	ctx context.Context,

	message channels.AuthChannelEnvelopeMarshalerKafka,
) error {
	return o.Channel.PublishAuthRequestMsg(ctx, message)
}
