// Code generated by go-asyncapi tool. DO NOT EDIT.

package operations

import (
	"context"
	"github.com/bdragon300/go-asyncapi/run"
	"site-authorization/asyncapi/channels"
	"site-authorization/asyncapi/messages"
	"site-authorization/asyncapi/proto/kafka"
)

type AuthResponseOperationServerKafka interface {
	OpenAuthChannelKafka(context.Context, channels.AuthChannelParameters, run.AnySecurityScheme) (*channels.AuthChannelKafka, error)
	OpenAuthResponseOperationKafka(context.Context, channels.AuthChannelParameters) (*AuthResponseOperationKafka, error)
	Producer() kafka.Producer
	Consumer() kafka.Consumer
}

func OpenAuthResponseOperationKafka(
	ctx context.Context,
	server AuthResponseOperationServerKafka,
	params channels.AuthChannelParameters,

) (*AuthResponseOperationKafka, error) {
	ch, err := channels.OpenAuthChannelKafka(
		ctx,
		server,
		params,
		nil,
		nil,
	)
	if err != nil {
		return nil, err
	}

	return &AuthResponseOperationKafka{
		Channel: ch,
	}, nil
}

type AuthResponseOperationChannelKafka interface {
	Close() error

	SealAuthResponseMsg(kafka.EnvelopeWriter, channels.AuthChannelEnvelopeMarshalerKafka) error
	PublishAuthResponseMsg(context.Context, channels.AuthChannelEnvelopeMarshalerKafka) error

	UnsealAuthResponseMsg(kafka.EnvelopeReader, channels.AuthChannelEnvelopeUnmarshalerKafka) error
	SubscribeAuthResponseMsg(context.Context, func(messages.AuthResponseMsgReceiver)) error
}

type AuthResponseOperationKafka struct {
	Channel AuthResponseOperationChannelKafka
}

func (c AuthResponseOperationKafka) Close() error {
	return c.Channel.Close()
}

func (o AuthResponseOperationKafka) UnsealAuthResponseMsg(
	envelope kafka.EnvelopeReader,
	message channels.AuthChannelEnvelopeUnmarshalerKafka,
) error {
	return o.Channel.UnsealAuthResponseMsg(envelope, message)
}

func (o AuthResponseOperationKafka) SubscribeAuthResponseMsg(
	ctx context.Context,
	cb func(message messages.AuthResponseMsgReceiver),
) (err error) {
	return o.Channel.SubscribeAuthResponseMsg(ctx, cb)
}
