// Code generated by go-asyncapi tool. DO NOT EDIT.

package http

import (
	"context"
	"net/url"

	runHttp "github.com/bdragon300/go-asyncapi/run/http"
)

func NewProducer(serverURL *url.URL, bindings *runHttp.ServerBindings) *ProduceClient {
	return &ProduceClient{
		bindings:  bindings,
		serverURL: serverURL,
	}
}

type ProduceClient struct {
	bindings  *runHttp.ServerBindings
	serverURL *url.URL
}

func (p ProduceClient) Publisher(_ context.Context, address string, chb *runHttp.ChannelBindings, opb *runHttp.OperationBindings) (runHttp.Publisher, error) {
	return NewPublisher(chb, opb, p.serverURL), nil
}
