name: go test
on: [push]
jobs:
  run_tests:
    name: go test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.24'
      - run: go test -race -covermode=atomic -coverprofile=coverage.out ./...
