name: Build docs site
on:
  push:
    branches:
      - master

defaults:
  run:
    working-directory: ./docs/go-asyncapi

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true
      - name: Build
        run: hugo --minify
      - name: Test
        run: pwd
      - name: Test2
        run: ls -la
      - name: Upload static files as artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/go-asyncapi/public

  deploy_docs:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
